import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, Cat, Check, Clock3, Coffee, ExternalLink, Eye, EyeOff, Loader2, LogOut, RefreshCw, Save, Settings2, Users, X } from 'lucide-react';
import LanguageSelect from './LanguageSelect.jsx';
import { contentLocales, defaultData, localized, normalizeAdminData, validationErrors } from './src/data/adminData.js';
import { useLanguage } from './src/i18n/LanguageProvider.jsx';

const labels={
  pl:{login:'Logowanie do panelu',password:'Hasło administratora',enter:'Zaloguj się',notReady:'Panel nie jest jeszcze połączony z bezpiecznym magazynem.',published:'Zmiany zostały opublikowane.',save:'Opublikuj zmiany',logout:'Wyloguj',reload:'Pobierz ponownie',editor:'Język treści',dirty:'Masz nieopublikowane zmiany.',failed:'Nie udało się wykonać operacji. Spróbuj ponownie.',conflict:'Treść została zmieniona w innym oknie. Pobrano najnowszą wersję.',invalid:'Popraw zaznaczone pola:',updated:'Ostatnia publikacja',visible:'Widoczne na stronie',group:'Kategoria',story:'Historia / opis',remove:'Usuń',showPassword:'Pokaż lub ukryj hasło'},
  ru:{login:'Вход в админ-панель',password:'Пароль администратора',enter:'Войти',notReady:'Панель ещё не подключена к защищённому хранилищу.',published:'Изменения опубликованы.',save:'Опубликовать изменения',logout:'Выйти',reload:'Загрузить заново',editor:'Язык контента',dirty:'Есть неопубликованные изменения.',failed:'Не удалось выполнить операцию. Попробуйте ещё раз.',conflict:'Данные изменены в другом окне. Загружена свежая версия.',invalid:'Исправьте поля:',updated:'Последняя публикация',visible:'Показывать на сайте',group:'Категория',story:'История / описание',remove:'Удалить',showPassword:'Показать или скрыть пароль'},
  en:{login:'Admin sign in',password:'Administrator password',enter:'Sign in',notReady:'The panel is not connected to secure storage yet.',published:'Changes have been published.',save:'Publish changes',logout:'Sign out',reload:'Reload',editor:'Content language',dirty:'You have unpublished changes.',failed:'The operation failed. Please try again.',conflict:'Content changed in another window. The latest version was loaded.',invalid:'Please fix:',updated:'Last published',visible:'Visible on site',group:'Category',story:'Story / description',remove:'Remove',showPassword:'Show or hide password'}
};
const groupText={coffee:localized('Kawa','Кофе','Coffee'),other:localized('Inne napoje','Другие напитки','Other drinks'),food:localized('Jedzenie','Еда','Food'),sweet:localized('Słodkości','Сладости','Sweets')};
const statusText={open:localized('Zapisy otwarte','Запись открыта','Registration open'),planned:localized('Planowane','Запланировано','Planned'),closed:localized('Zakończone','Завершено','Finished'),calm:localized('Spokojnie','Свободно','Quiet'),busy:localized('Umiarkowanie zajęte','Умеренно занято','Moderately busy'),'almost-full':localized('Prawie pełno','Почти нет мест','Almost full'),full:localized('Brak miejsc','Мест нет','Full'),resident:localized('Stały rezydent','Постоянный житель','Permanent resident'),adoption:localized('Szuka domu','Ищет дом','Looking for a home'),reserved:localized('Adopcja w toku','Усыновление оформляется','Adoption pending')};
const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.error||'REQUEST_FAILED'),{status:response.status,body});return body;};

export default function AdminPage(){
  const {language,tr}=useLanguage(), t=labels[language]||labels.pl;
  const [session,setSession]=useState({loading:typeof window!=='undefined',authenticated:false,configured:true});
  const [data,setData]=useState(()=>normalizeAdminData(defaultData));
  const [locale,setLocale]=useState(language);
  const [password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false);
  const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(null);
  const counter=useRef(0);
  const load=async()=>{setBusy(true);setMessage(null);try{const body=await api('/api/content');setData(normalizeAdminData(body.data));setDirty(false);}catch{setMessage({kind:'error',text:t.failed});}finally{setBusy(false);}};
  useEffect(()=>{api('/api/auth/session').then(body=>{setSession({loading:false,...body});if(body.authenticated)load();}).catch(()=>setSession({loading:false,authenticated:false,configured:false}));},[]);
  useEffect(()=>{const warn=event=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const change=updater=>{setData(current=>typeof updater==='function'?updater(current):updater);setDirty(true);setMessage(null);};
  const update=(section,index,key,value)=>change(current=>({...current,[section]:current[section].map((row,i)=>i===index?{...row,[key]:value}:row)}));
  const updateText=(section,index,key,value)=>change(current=>({...current,[section]:current[section].map((row,i)=>i===index?{...row,[key]:{...row[key],[locale]:value}}:row)}));
  const remove=(section,index)=>change(current=>({...current,[section]:current[section].filter((_,i)=>i!==index)}));
  const signIn=async event=>{event.preventDefault();setBusy(true);setMessage(null);try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({password})});setPassword('');setSession(current=>({...current,authenticated:true}));await load();}catch(error){setMessage({kind:'error',text:error.status===429?'Too many attempts. Try again in 10 minutes.':error.status===503?t.notReady:'Incorrect password.'});}finally{setBusy(false);}};
  const logout=async()=>{setBusy(true);try{await api('/api/auth/logout',{method:'POST'});}catch{}setSession(current=>({...current,authenticated:false}));setBusy(false);};
  const save=async()=>{const errors=validationErrors(data);if(errors.length){setMessage({kind:'error',text:`${t.invalid} ${errors.join(', ')}`});return;}setBusy(true);setMessage(null);try{const body=await api('/api/content',{method:'PUT',body:JSON.stringify(data)});setData(normalizeAdminData(body.data));setDirty(false);setMessage({kind:'success',text:t.published});}catch(error){if(error.status===409&&error.body?.data){setData(normalizeAdminData(error.body.data));setDirty(false);setMessage({kind:'error',text:t.conflict});}else if(error.status===401)setSession(current=>({...current,authenticated:false}));else setMessage({kind:'error',text:t.failed});}finally{setBusy(false);}};
  if(session.loading)return <Splash><Loader2 className="animate-spin text-sky-500" size={34}/></Splash>;
  if(!session.authenticated)return <Login t={t} tr={tr} configured={session.configured} password={password} setPassword={setPassword} show={showPassword} setShow={setShowPassword} busy={busy} message={message} onSubmit={signIn}/>;
  return <div className="min-h-screen bg-[#f7f8f4] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-8"><Brand/><div className="flex flex-wrap items-center gap-2"><LanguageSelect/><Link to="/" className="admin-action"><ExternalLink size={15}/>{tr('Открыть сайт')}</Link><button onClick={logout} className="admin-action"><LogOut size={15}/>{t.logout}</button></div></div></header>
    <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[.2em] text-sky-600"><Settings2 size={16}/>{tr('Panel administracyjny')}</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{tr('Управление кафе')}</h1><p className="mt-3 text-sm text-slate-500">{t.updated}: {data.updatedAt?new Intl.DateTimeFormat(language,{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.updatedAt)):'—'} · rev. {data.revision}</p></div><div className="flex flex-wrap gap-2"><button onClick={load} disabled={busy} className="admin-action"><RefreshCw size={16}/>{t.reload}</button><button onClick={save} disabled={busy||!dirty} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-5 py-2.5 text-sm font-extrabold text-white disabled:opacity-40">{busy?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>} {t.save}</button></div></div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-3"><strong className="px-2 text-sm">{t.editor}</strong><div className="flex gap-1">{contentLocales.map(code=><button key={code} onClick={()=>setLocale(code)} className={`rounded-full px-4 py-2 text-xs font-black uppercase ${locale===code?'bg-sky-500 text-white':'bg-slate-100 text-slate-600'}`}>{code}</button>)}</div></div>
      {dirty&&<Notice kind="warning">{t.dirty}</Notice>}{message&&<Notice kind={message.kind}>{message.text}</Notice>}
      <div className="grid gap-5 lg:grid-cols-2">
        <Panel icon={Clock3} title={tr('Расписание')}><Rows>{data.schedule.map((row,i)=><Row key={row.id}><Field label={tr('День')} value={row.day[locale]} onChange={v=>updateText('schedule',i,'day',v)}/><Field label={tr('Часы работы')} value={row.hours[locale]} onChange={v=>updateText('schedule',i,'hours',v)}/><Remove label={t.remove} onClick={()=>remove('schedule',i)}/></Row>)}</Rows><Add onClick={()=>change(c=>({...c,schedule:[...c.schedule,{id:`schedule-${Date.now()}-${++counter.current}`,day:localized('Nowy dzień','Новый день','New day'),hours:localized('11:00–20:00')}]}))}>{tr('Добавить день')}</Add></Panel>
        <Panel icon={Users} title={tr('Свободные места')}><SelectField label={tr('Статус')} value={data.availability.status} onChange={v=>change(c=>({...c,availability:{...c.availability,status:v}}))} options={['calm','busy','almost-full','full'].map(v=>[v,statusText[v][locale]])}/><Field label={tr('Подпись')} value={data.availability.note[locale]} onChange={v=>change(c=>({...c,availability:{...c.availability,note:{...c.availability.note,[locale]:v}}}))}/></Panel>
        <Panel icon={Coffee} title={tr('Цены меню')} wide><div className="grid gap-3 md:grid-cols-2">{data.prices.map((row,i)=><Card key={row.id}><div className="grid gap-2 sm:grid-cols-[1fr_120px]"><Field label={tr('Позиция меню')} value={row.name[locale]} onChange={v=>updateText('prices',i,'name',v)}/><Field label={tr('Цена')} value={row.price} onChange={v=>update('prices',i,'price',v)}/></div><SelectField label={t.group} value={row.group} onChange={v=>update('prices',i,'group',v)} options={['coffee','other','food','sweet'].map(value=>[value,groupText[value][language]])}/><div className="mt-2 flex items-center justify-between"><Toggle label={t.visible} checked={row.enabled} onChange={v=>update('prices',i,'enabled',v)}/><Remove label={t.remove} onClick={()=>remove('prices',i)}/></div></Card>)}</div><Add onClick={()=>change(c=>({...c,prices:[...c.prices,{id:`menu-${Date.now()}`,group:'coffee',name:localized('Nowa pozycja','Новая позиция','New item'),price:'0 zł',enabled:true}]}))}>{tr('Добавить позицию')}</Add></Panel>
        <Panel icon={CalendarDays} title={tr('События')} wide><div className="grid gap-3 md:grid-cols-2">{data.events.map((row,i)=><Card key={row.id}><Field label={tr('Название события')} value={row.title[locale]} onChange={v=>updateText('events',i,'title',v)}/><Field label={tr('Дата события')} value={row.date[locale]} onChange={v=>updateText('events',i,'date',v)}/><div className="grid grid-cols-2 gap-2"><Field label={tr('Количество мест')} type="number" value={row.places} onChange={v=>update('events',i,'places',v)}/><SelectField label={tr('Статус события')} value={row.status} onChange={v=>update('events',i,'status',v)} options={['open','planned','closed'].map(v=>[v,statusText[v][locale]])}/></div><div className="mt-2 flex items-center justify-between"><Toggle label={t.visible} checked={row.enabled} onChange={v=>update('events',i,'enabled',v)}/><Remove label={t.remove} onClick={()=>remove('events',i)}/></div></Card>)}</div><Add onClick={()=>change(c=>({...c,events:[...c.events,{id:`event-${Date.now()}`,title:localized('Nowe wydarzenie','Новое событие','New event'),date:localized('Data i godzina','Дата и время','Date and time'),places:'10',status:'planned',enabled:true}]}))}>{tr('Добавить событие')}</Add></Panel>
        <Panel icon={Cat} title={tr('Информация о котах')} wide><div className="grid gap-3 md:grid-cols-3">{data.cats.map((row,i)=><Card key={row.id}><div className="grid grid-cols-2 gap-2"><Field label={tr('Имя кота')} value={row.name} onChange={v=>update('cats',i,'name',v)}/><Field label="Slug" value={row.slug} readOnly/></div><SelectField label={tr('Статус кота')} value={row.status} onChange={v=>update('cats',i,'status',v)} options={['resident','adoption','reserved'].map(v=>[v,statusText[v][locale]])}/><Field label={tr('Короткое описание кота')} value={row.note[locale]} onChange={v=>updateText('cats',i,'note',v)}/><Field multiline label={t.story} value={row.intro[locale]} onChange={v=>updateText('cats',i,'intro',v)}/><Toggle label={t.visible} checked={row.enabled} onChange={v=>update('cats',i,'enabled',v)}/></Card>)}</div></Panel>
      </div>
    </main></div>;
}

function Login({t,tr,configured,password,setPassword,show,setShow,busy,message,onSubmit}){return <Splash><div className="w-full max-w-md rounded-[2rem] border border-slate-200 bg-white p-7 shadow-xl sm:p-9"><Brand/><p className="mt-8 text-sm font-extrabold uppercase tracking-[.18em] text-sky-600">{tr('Panel administracyjny')}</p><h1 className="mt-2 text-3xl font-black">{t.login}</h1>{!configured&&<Notice kind="warning">{t.notReady}</Notice>}{message&&<Notice kind="error">{message.text}</Notice>}<form onSubmit={onSubmit} className="mt-6"><label className="admin-label">{t.password}<span className="relative mt-2 block"><input autoFocus autoComplete="current-password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="admin-input pr-12"/><button type="button" onClick={()=>setShow(!show)} aria-label={t.showPassword} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-slate-500">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><button disabled={busy||!password} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-slate-950 px-5 py-3 font-extrabold text-white disabled:opacity-40">{busy&&<Loader2 className="animate-spin" size={17}/>} {t.enter}</button></form><Link to="/" className="mt-5 block text-center text-sm font-bold text-sky-600">← {tr('Открыть сайт')}</Link></div></Splash>}
function Splash({children}){return <div className="grid min-h-screen place-items-center bg-[#f7f8f4] p-5">{children}</div>}
function Brand(){return <Link to="/" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-full bg-sky-500 text-white"><Cat size={20}/></span><span className="text-lg font-extrabold">Niebieski Kot<span className="text-sky-500">.</span></span></Link>}
function Panel({icon:Icon,title,children,wide=false}){return <section className={`rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7 ${wide?'lg:col-span-2':''}`}><h2 className="mb-5 flex items-center gap-3 text-xl font-black"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-100 text-sky-600"><Icon size={19}/></span>{title}</h2>{children}</section>}
function Rows({children}){return <div className="space-y-3">{children}</div>}
function Row({children}){return <div className="grid items-end gap-2 sm:grid-cols-[1fr_1fr_auto]">{children}</div>}
function Card({children}){return <div className="rounded-2xl bg-slate-50 p-4">{children}</div>}
function Field({label,value,onChange=()=>{},type='text',multiline=false,readOnly=false}){const Tag=multiline?'textarea':'input';return <label className="admin-label">{label}<Tag type={type} min={type==='number'?'0':undefined} maxLength={500} value={value} readOnly={readOnly} onChange={e=>onChange(e.target.value)} className={`admin-input mt-1.5 min-h-11 ${readOnly?'bg-slate-100 text-slate-500':''}`}/></label>}
function SelectField({label,value,onChange,options}){return <label className="admin-label mb-2">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="admin-input mt-1.5">{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Toggle({label,checked,onChange}){return <label className="flex cursor-pointer items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-sky-500"/>{label}</label>}
function Remove({onClick,label}){return <button type="button" aria-label={label} onClick={onClick} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-400 hover:border-rose-300 hover:text-rose-500"><X size={16}/></button>}
function Add({onClick,children}){return <button type="button" onClick={onClick} className="mt-4 rounded-full border border-dashed border-sky-300 px-4 py-2 text-sm font-bold text-sky-700 hover:bg-sky-50">+ {children}</button>}
function Notice({kind,children}){const style=kind==='success'?'border-emerald-200 bg-emerald-50 text-emerald-800':kind==='warning'?'border-amber-200 bg-amber-50 text-amber-900':'border-rose-200 bg-rose-50 text-rose-800';return <p role={kind==='error'?'alert':'status'} className={`my-4 flex items-start gap-2 rounded-2xl border p-4 text-sm font-semibold ${style}`}>{kind==='success'&&<Check size={17}/>} {children}</p>}
