import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, CalendarDays, Cat, Check, ChevronLeft, ChevronRight, Clock3, Coffee, Globe2, Heart, HeartHandshake, Instagram, MapPin, Menu, MessageCircle, PawPrint, Send, ShieldCheck, ShoppingBasket, X } from 'lucide-react';
import BookingModal from './BookingModal.jsx';
import SupportModal from './SupportModal.jsx';

const cats = [
  { name: 'Luna', linkLabel: 'Poznaj Lunę', note: '4 lata · spokojna obserwatorka', story: 'Trafiła do nas po przeprowadzce opiekunów. Najchętniej siedzi przy oknie i sama wybiera moment na głaskanie.', image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=85&w=900&auto=format&fit=crop', slug: 'luna' },
  { name: 'Mochi', linkLabel: 'Poznaj Mochiego', note: '6 lat · mistrz drzemek', story: 'Łagodny kocur znaleziony na działkach. Kocha miękkie koce, spokojne rozmowy i ludzi z książką na kolanach.', image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=85&w=900&auto=format&fit=crop', slug: 'mochi' },
  { name: 'Pixel', linkLabel: 'Poznaj Pixela', note: '2 lata · pierwszy do zabawy', story: 'Najmłodszy w ekipie i kandydat do adopcji. Wędkę wypatrzy z drugiego końca sali, a potem zasypia pod stolikiem.', image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=85&w=900&auto=format&fit=crop', slug: 'pixel' },
];
const catTranslations = {
  ru: {
    luna: { linkLabel: 'Познакомиться с Луной', note: '4 года · спокойная наблюдательница', story: 'Она попала к нам после переезда своих хозяев. Больше всего любит сидеть у окна и сама выбирает момент для ласки.' },
    mochi: { linkLabel: 'Познакомиться с Мочи', note: '6 лет · мастер сна', story: 'Мягкий кот, найденный на дачных участках. Любит тёплые пледы, спокойные разговоры и людей с книгой на коленях.' },
    pixel: { linkLabel: 'Познакомиться с Пикселем', note: '2 года · первым готов играть', story: 'Самый младший в команде и кандидат на усыновление. Замечает удочку из другого конца комнаты, а потом засыпает под столом.' },
  },
  en: {
    luna: { linkLabel: 'Meet Luna', note: '4 years · quiet observer', story: 'She came to us after her guardians moved. She loves sitting by the window and chooses the moment for affection herself.' },
    mochi: { linkLabel: 'Meet Mochi', note: '6 years · nap champion', story: 'A gentle tomcat found near allotments. He loves soft blankets, quiet conversations and people reading with a book on their lap.' },
    pixel: { linkLabel: 'Meet Pixel', note: '2 years · first to play', story: 'The youngest of the group and looking for a home. He spots a toy wand from across the room, then falls asleep under the table.' },
  },
};
const rules = [
  'Przed wejściem do strefy kotów dezynfekujemy ręce.',
  'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.',
  'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.',
  'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.',
  'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.',
];
const faqItems = [
  { question: 'Czy można przyjść z dziećmi?', answer: 'Tak. Zapraszamy dzieci od 8 lat, zawsze pod opieką dorosłego. Prosimy, aby dzieci nie biegały i pozwalały kotom samodzielnie decydować o kontakcie.' },
  { question: 'Mam alergię na koty — czy mogę odwiedzić kawiarnię?', answer: 'Wizyta wiąże się z obecnością sierści i alergenów, dlatego nie możemy zagwarantować bezpiecznych warunków dla osób z alergią. Jeśli objawy są łagodne, przed rezerwacją skonsultuj wizytę z lekarzem i poinformuj obsługę.' },
  { question: 'Czy można przynieść własne jedzenie?', answer: 'Nie. Ze względów higienicznych i bezpieczeństwa kotów własne jedzenie oraz napoje zostawiamy poza lokalem. Na miejscu czeka menu kawiarni z opcjami wegetariańskimi.' },
  { question: 'Czy można przyjść z własnym zwierzęciem?', answer: 'Nie. Nawet spokojny pies lub kot może stresować naszych rezydentów. Wyjątek stanowią certyfikowane psy asystujące — prosimy o wcześniejszy kontakt.' },
  { question: 'Czy trzeba rezerwować miejsce?', answer: 'W tygodniu zwykle wystarczy przyjść, ale rezerwacja daje pewność miejsca. W weekendy i podczas wydarzeń polecamy zarezerwować stolik z wyprzedzeniem.' },
];
const events = [
  { icon: Heart, tag: 'Każda niedziela', title: 'Joga z kotami', text: 'Łagodna praktyka dla początkujących, spokojna muzyka i koty spacerujące po sali.', meta: '10:00 · 60 minut · 45 zł' },
  { icon: Coffee, tag: 'Każdy piątek', title: 'Wieczór gier planszowych', text: 'Małe grupy, przytulne gry i gorący napój z naszej karty.', meta: '18:00 · 90 minut · 25 zł' },
  { icon: Cat, tag: 'Dwie soboty w miesiącu', title: 'Czytania i warsztaty', text: 'Opowieści o zwierzętach, twórcze zajęcia i spokojny format dla całej rodziny.', meta: '12:00 · 75 minut · od 20 zł' },
  { icon: PawPrint, tag: 'Pierwsza niedziela miesiąca', title: 'Dzień adopcji', text: 'Poznaj nasze koty, porozmawiaj z wolontariuszami i przygotuj się do odpowiedzialnej adopcji.', meta: 'Wstęp wolny · obowiązują zapisy' },
];
const contentTranslations = {
  ru: {
    'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Перед входом в зону котов дезинфицируем руки.',
    'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.': 'Позволяем котам самим решать, нужен ли контакт — не будим их и не берём на руки.',
    'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.': 'Фотографируем без вспышки и уважаем кошачий покой.',
    'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.': 'Дети могут приходить только под присмотром взрослых; детали уточнит команда.',
    'Każda niedziela': 'Каждое воскресенье', 'Każdy piątek': 'Каждую пятницу', 'Dwie soboty w miesiącu': 'Две субботы в месяц', 'Pierwsza niedziela miesiąca': 'Первое воскресенье месяца',
    'Łagodna praktyka dla początkujących, spokojna muzyka i koty spacerujące po sali.': 'Мягкая практика для начинающих, спокойная музыка и коты, гуляющие по залу.',
    'Małe grupy, przytulne gry i gorący napój z naszej karty.': 'Небольшие компании, уютные игры и горячий напиток из нашего меню.',
    'Opowieści o zwierzętach, twórcze zajęcia i spokojny format dla całej rodziny.': 'Истории о животных, творческие занятия и спокойный формат для всей семьи.',
    'Poznaj nasze koty, porozmawiaj z wolontariuszami i przygotuj się do odpowiedzialnej adopcji.': 'Познакомьтесь с нашими котами, поговорите с волонтёрами и подготовьтесь к ответственному усыновлению.',
    'Wstęp wolny · obowiązują zapisy': 'Вход свободный · нужна запись', 'Gotowy na spotkanie': 'Готов к встрече'
  },
  en: {
    'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Please sanitise your hands before entering the cat area.',
    'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.': 'Let the cats choose contact — do not wake them or pick them up.',
    'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.': 'Please take photos without flash and respect the cats’ calm.',
    'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.': 'Children are welcome with continuous adult supervision; ask the team for details.',
    'Każda niedziela': 'Every Sunday', 'Każdy piątek': 'Every Friday', 'Dwie soboty w miesiącu': 'Two Saturdays each month', 'Pierwsza niedziela miesiąca': 'First Sunday of the month',
    'Łagodna praktyka dla początkujących, spokojna muzyka i koty spacerujące po sali.': 'A gentle practice for beginners, calm music and cats wandering around the room.',
    'Małe grupy, przytulne gry i gorący napój z naszej karty.': 'Small groups, cosy games and a hot drink from our menu.',
    'Opowieści o zwierzętach, twórcze zajęcia i spokojny format dla całej rodziny.': 'Animal stories, creative activities and a calm format for the whole family.',
    'Poznaj nasze koty, porozmawiaj z wolontariuszami i przygotuj się do odpowiedzialnej adopcji.': 'Meet our cats, talk with volunteers and prepare for responsible adoption.',
    'Wstęp wolny · obowiązują zapisy': 'Free entry · registration required', 'Gotowy na spotkanie': 'Ready to meet'
  }
};
const languageCopy = {
  pl: { nav: ['O nas', 'Koty', 'Menu', 'Zasady', 'Wydarzenia', 'Wesprzyj', 'Wizyta'], ask: 'Zapytaj nas', booking: 'Zarezerwuj stolik', cats: 'Poznaj koty', eyebrow: 'Kocia kawiarnia · Opole', hero: 'Zwolnij. Kawa stygnie, koty nie.', intro: 'Spokojne miejsce na dobrą kawę, miękki fotel i spotkanie z kotami, które naprawdę nadają temu miejscu rytm.' },
  ru: { nav: ['О нас', 'Коты', 'Меню', 'Правила', 'События', 'Поддержать', 'Визит'], ask: 'Спросить нас', booking: 'Забронировать столик', cats: 'Познакомиться с котами', eyebrow: 'Котокафе · Ополе', hero: 'Замедлись. Кофе остывает, коты — нет.', intro: 'Уютное место для хорошего кофе, мягкого кресла и встречи с котами, которые задают этому месту свой ритм.' },
  en: { nav: ['About', 'Cats', 'Menu', 'Rules', 'Events', 'Support', 'Visit'], ask: 'Ask us', booking: 'Book a table', cats: 'Meet the cats', eyebrow: 'Cat café · Opole', hero: 'Slow down. Coffee cools, cats don’t.', intro: 'A calm place for good coffee, a soft chair and time with cats who give this café its own rhythm.' },
};
const pageCopy = {
  pl: {
    open: 'Otwarte teraz · do 20:00', monday: 'Poniedziałek · koty odpoczywają', today: 'Dziś od 11:00', adopt: 'Wspieramy adopcje', coffee: 'Specialty coffee', homeTitle: 'Tu kot wybiera Ciebie', homeText: 'Usiądź wygodnie i daj mu chwilę.', aboutLabel: 'Nasza idea', aboutTitle: 'Dobre rzeczy dzieją się wolniej.', aboutOne: 'Tworzymy kameralną kawiarnię, w której dobrostan kotów jest równie ważny jak smak espresso.', aboutTwo: 'Każdy rezydent ma własną historię, charakter i przestrzeń. Ty dostajesz chwilę oddechu — on wybór, czy chce dołączyć.', catsLabel: 'Nasi gospodarze', catsTitle: 'Poznaj ekipę.', catsText: 'Każdy inny. Każdy u siebie. Pixel szuka domu, Luna i Mochi są stałymi gospodarzami.', menuLabel: 'Jedzenie i napoje', menuTitle: 'Kocia karta ma własne miejsce.', menuText: 'Kawy specialty, śniadania, lekkie dania i domowe słodkości — teraz w przejrzystym menu z cenami.', menuButton: 'Otwórz pełne menu', rulesLabel: 'Koci savoir-vivre', rulesTitle: 'Kilka zasad. Dużo spokoju.', rulesText: 'To dom naszych rezydentów. Proste reguły sprawiają, że wszystkim — na dwóch i czterech łapach — jest tu dobrze.', faqLabel: 'FAQ pierwszej wizyty', faqTitle: 'Dobrze wiedzieć przed przyjściem.', visitLabel: 'Zanim wpadniesz', visitTitle: 'Zaplanuj miękkie lądowanie.', book: 'Zarezerwuj stolik', ask: 'Zapytaj asystenta', map: 'Pokaż mapę', supportLabel: 'Dla naszych kotów', supportTitle: 'Mały gest. Dużo spokoju.', supportText: 'Opieka weterynaryjna, karma i spokojne kryjówki są ważniejsze niż kolejna zabawka. Wybierz sposób, w jaki chcesz dołożyć swoją cegiełkę.', supportButton: 'Wesprzyj koty', needsLabel: 'Lista potrzeb', needsTitle: 'Co przyda się najbardziej?', needsText: 'Rzeczy można przynieść po wcześniejszym kontakcie z obsługą. Najpierw sprawdzimy, czego aktualnie potrzebują koty.', eventsLabel: 'W kalendarzu kociej kawiarni', eventsTitle: 'Wydarzenia, na które chce się wracać.', eventsText: 'Małe spotkania w spokojnym rytmie. Liczba miejsc jest ograniczona, dlatego warto zapisać się wcześniej.', eventsButton: 'Zapisz się'
  },
  ru: {
    open: 'Открыто · до 20:00', monday: 'Понедельник · коты отдыхают', today: 'Сегодня с 11:00', adopt: 'Помогаем усыновлению', coffee: 'Авторский кофе', homeTitle: 'Здесь кот выбирает тебя', homeText: 'Устраивайся поудобнее и дай ему время.', aboutLabel: 'Наша идея', aboutTitle: 'Хорошие вещи происходят медленнее.', aboutOne: 'Мы создаём камерное кафе, где благополучие котов так же важно, как вкус эспрессо.', aboutTwo: 'У каждого жителя своя история, характер и пространство. Ты получаешь передышку, а кот — право самому выбрать контакт.', catsLabel: 'Наши хозяева', catsTitle: 'Познакомься с командой.', catsText: 'Все разные и каждый у себя дома. Пиксель ищет дом, Луна и Мочи — постоянные жители.', menuLabel: 'Еда и напитки', menuTitle: 'У котокафе есть своё меню.', menuText: 'Авторский кофе, завтраки, лёгкие блюда и домашние десерты — всё с понятными ценами.', menuButton: 'Открыть меню', rulesLabel: 'Кошачьи правила', rulesTitle: 'Несколько правил. Много спокойствия.', rulesText: 'Это дом наших жителей. Простые правила помогают хорошо себя чувствовать и людям, и котам.', faqLabel: 'FAQ первого визита', faqTitle: 'Что важно знать заранее.', visitLabel: 'Перед визитом', visitTitle: 'Запланируй мягкую посадку.', book: 'Забронировать столик', ask: 'Спросить ассистента', map: 'Открыть карту', supportLabel: 'Для наших котов', supportTitle: 'Маленький жест. Большое спокойствие.', supportText: 'Ветеринарная помощь, корм и тихие укрытия важнее очередной игрушки. Выбери свой способ помочь.', supportButton: 'Поддержать котов', needsLabel: 'Список нужд', needsTitle: 'Что сейчас нужнее всего?', needsText: 'Вещи можно принести после связи с командой. Сначала уточним, что котам нужно сейчас.', eventsLabel: 'В календаре котокафе', eventsTitle: 'События, ради которых хочется вернуться.', eventsText: 'Небольшие встречи в спокойном ритме. Количество мест ограничено, поэтому лучше записаться заранее.', eventsButton: 'Записаться'
  },
  en: {
    open: 'Open now · until 20:00', monday: 'Monday · cats are resting', today: 'Today from 11:00', adopt: 'We support adoption', coffee: 'Specialty coffee', homeTitle: 'Here, the cat chooses you', homeText: 'Make yourself comfortable and give them a moment.', aboutLabel: 'Our idea', aboutTitle: 'Good things happen more slowly.', aboutOne: 'We are creating an intimate café where cat wellbeing matters as much as the taste of espresso.', aboutTwo: 'Every resident has a story, personality and space. You get a moment to breathe — they get the choice to connect.', catsLabel: 'Our hosts', catsTitle: 'Meet the team.', catsText: 'Each one is different and at home here. Pixel is looking for a home; Luna and Mochi are resident hosts.', menuLabel: 'Food and drinks', menuTitle: 'The cat café has its own menu.', menuText: 'Specialty coffee, breakfast, light dishes and homemade sweets — all with clear prices.', menuButton: 'Open full menu', rulesLabel: 'Cat etiquette', rulesTitle: 'A few rules. Lots of calm.', rulesText: 'This is our residents’ home. Simple rules help everyone — on two and four legs — feel comfortable.', faqLabel: 'First visit FAQ', faqTitle: 'Good to know before you come.', visitLabel: 'Before you visit', visitTitle: 'Plan a soft landing.', book: 'Book a table', ask: 'Ask the assistant', map: 'Show map', supportLabel: 'For our cats', supportTitle: 'A small gesture. A lot of calm.', supportText: 'Veterinary care, food and quiet hideaways matter more than another toy. Choose how you would like to help.', supportButton: 'Support the cats', needsLabel: 'Wish list', needsTitle: 'What helps most?', needsText: 'Please contact the team before bringing items so we can confirm what the cats need right now.', eventsLabel: 'In the cat café calendar', eventsTitle: 'Events worth coming back for.', eventsText: 'Small gatherings at a calm pace. Places are limited, so early registration is recommended.', eventsButton: 'Sign up'
  },
};
const domTranslations = {
  pl: { 'Открыть профиль': 'Otwórz profil' },
  ru: {
    'zero pośpiechu ✦': 'никакой спешки ✦', 'Wspieramy adopcje': 'Помогаем усыновлению', 'Specialty coffee': 'Авторский кофе', 'Nasza idea': 'Наша идея', 'Dobre rzeczy dzieją się wolniej.': 'Хорошие вещи происходят медленнее.', 'Tworzymy kameralną kawiarnię, w której dobrostan kotów jest równie ważny jak smak espresso.': 'Мы создаём камерное кафе, где благополучие котов так же важно, как вкус эспрессо.', 'Każdy rezydent ma własną historię, charakter i przestrzeń. Ty dostajesz chwilę oddechu — on wybór, czy chce dołączyć.': 'У каждого жителя своя история, характер и пространство. Ты получаешь передышку, а кот сам выбирает контакт.', 'Nasi gospodarze': 'Наши хозяева', 'Poznaj ekipę.': 'Познакомься с командой.', 'Każdy inny. Każdy u siebie. Pixel szuka domu, Luna i Mochi są stałymi gospodarzami.': 'Все разные и каждый у себя дома. Пиксель ищет дом, Луна и Мочи — постоянные жители.', 'Jedzenie i napoje': 'Еда и напитки', 'Kocia karta ma własne miejsce.': 'У котокафе есть своё меню.', 'Kawy specialty, śniadania, lekkie dania i domowe słodkości — teraz w przejrzystym menu z cenami.': 'Авторский кофе, завтраки, лёгкие блюда и домашние десерты — всё с понятными ценами.', 'Otwórz pełne menu': 'Открыть меню', 'Koci savoir-vivre': 'Кошачьи правила', 'Kilka zasad.': 'Несколько правил.', 'Dużo spokoju.': 'Много спокойствия.', 'To dom naszych rezydentów. Proste reguły sprawiają, że wszystkim — na dwóch i czterech łapach — jest tu dobrze.': 'Это дом наших жителей. Простые правила помогают хорошо себя чувствовать и людям, и котам.', 'FAQ pierwszej wizyty': 'FAQ первого визита', 'Dobrze wiedzieć przed przyjściem.': 'Что важно знать заранее.', 'Zanim wpadniesz': 'Перед визитом', 'Zaplanuj miękkie lądowanie.': 'Запланируй мягкую посадку.', 'Zarezerwuj stolik': 'Забронировать столик', 'Zapytaj asystenta': 'Спросить ассистента', 'Pokaż mapę': 'Открыть карту', 'Dla naszych kotów': 'Для наших котов', 'Mały gest.': 'Маленький жест.', 'Dużo spokoju.': 'Большое спокойствие.', 'Wesprzyj koty': 'Поддержать котов', 'Lista potrzeb': 'Список нужд', 'Co przyda się najbardziej?': 'Что сейчас нужнее всего?', 'W kalendarzu kociej kawiarni': 'В календаре котокафе', 'Wydarzenia, na które chce się wracać.': 'События, ради которых хочется вернуться.', 'Zapisz się': 'Записаться', 'Czy można przyjść z dziećmi?': 'Можно ли прийти с детьми?', 'Czy można przynieść własne jedzenie?': 'Можно ли принести свою еду?', 'Czy trzeba rezerwować miejsce?': 'Нужно ли бронировать место?', 'Joga z kotami': 'Йога с котами', 'Wieczór gier planszowych': 'Вечер настольных игр', 'Czytania i warsztaty': 'Чтения и мастер-классы', 'Dzień adopcji': 'День усыновления'
  },
  en: {
    'zero pośpiechu ✦': 'no rush ✦', 'Wspieramy adopcje': 'We support adoption', 'Specialty coffee': 'Specialty coffee', 'Nasza idea': 'Our idea', 'Dobre rzeczy dzieją się wolniej.': 'Good things happen more slowly.', 'Tworzymy kameralną kawiarnię, w której dobrostan kotów jest równie ważny jak smak espresso.': 'We are creating an intimate café where cat wellbeing matters as much as the taste of espresso.', 'Każdy rezydent ma własną historię, charakter i przestrzeń. Ty dostajesz chwilę oddechu — on wybór, czy chce dołączyć.': 'Every resident has a story, personality and space. You get a moment to breathe — they choose whether to connect.', 'Nasi gospodarze': 'Our hosts', 'Poznaj ekipę.': 'Meet the team.', 'Każdy inny. Każdy u siebie. Pixel szuka domu, Luna i Mochi są stałymi gospodarzami.': 'Each one is different and at home here. Pixel is looking for a home; Luna and Mochi are resident hosts.', 'Jedzenie i napoje': 'Food and drinks', 'Kocia karta ma własne miejsce.': 'The cat café has its own menu.', 'Kawy specialty, śniadania, lekkie dania i domowe słodkości — teraz w przejrzystym menu z cenami.': 'Specialty coffee, breakfast, light dishes and homemade sweets — all with clear prices.', 'Otwórz pełne menu': 'Open full menu', 'Koci savoir-vivre': 'Cat etiquette', 'Kilka zasad.': 'A few rules.', 'Dużo spokoju.': 'Lots of calm.', 'To dom naszych rezydentów. Proste reguły sprawiają, że wszystkim — na dwóch i czterech łapach — jest tu dobrze.': 'This is our residents’ home. Simple rules help everyone feel comfortable.', 'FAQ pierwszej wizyty': 'First visit FAQ', 'Dobrze wiedzieć przed przyjściem.': 'Good to know before you come.', 'Zanim wpadniesz': 'Before you visit', 'Zaplanuj miękkie lądowanie.': 'Plan a soft landing.', 'Zarezerwuj stolik': 'Book a table', 'Zapytaj asystenta': 'Ask the assistant', 'Pokaż mapę': 'Show map', 'Dla naszych kotów': 'For our cats', 'Mały gest.': 'A small gesture.', 'Dużo spokoju.': 'A lot of calm.', 'Wesprzyj koty': 'Support the cats', 'Lista potrzeb': 'Wish list', 'Co przyda się najbardziej?': 'What helps most?', 'W kalendarzu kociej kawiarni': 'In the cat café calendar', 'Wydarzenia, na które chce się wracać.': 'Events worth coming back for.', 'Zapisz się': 'Sign up', 'Czy można przyjść z dziećmi?': 'Can I bring children?', 'Czy można przynieść własne jedzenie?': 'Can I bring my own food?', 'Czy trzeba rezerwować miejsce?': 'Do I need a reservation?', 'Joga z kotami': 'Cat yoga', 'Wieczór gier planszowych': 'Board game night', 'Czytania i warsztaty': 'Readings and workshops', 'Dzień adopcji': 'Adoption day'
  },
};
const extraTranslations = {
  ru: {
    'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.': 'Свою еду и лакомства для котов оставляем за пределами кафе.', 'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Перед входом в зону котов дезинфицируем руки.', 'Nie budzimy ich i nie bierzemy na ręce.': 'Не будим котов и не берём их на руки.', 'Projekt koncepcyjny — adres, kontakt i bohaterowie są demonstracyjne.': 'Концептуальный проект — адрес, контакты и истории котов демонстрационные.', 'Niebieski Asystent': 'Ассистент Niebieski Kot', 'szybkie odpowiedzi': 'быстрые ответы', 'Piszę…': 'Печатаю…'
  },
  en: {
    'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.': 'Please leave your own food and cat treats outside the café.', 'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Please sanitise your hands before entering the cat area.', 'Nie budzimy ich i nie bierzemy na ręce.': 'Do not wake the cats or pick them up.', 'Projekt koncepcyjny — adres, kontakt i bohaterowie są demonstracyjne.': 'Concept project — the address, contact details and cat stories are demonstrational.', 'Niebieski Asystent': 'Niebieski Kot Assistant', 'szybkie odpowiedzi': 'quick answers', 'Piszę…': 'Typing…'
  },
};
const detailTranslations = {
  ru: {
    'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Перед входом в зону котов дезинфицируем руки.', 'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.': 'Позволяем котам самим решать, нужен ли контакт — не будим их и не берём на руки.', 'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.': 'Фотографируем без вспышки и уважаем кошачий покой.', 'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.': 'Дети могут приходить только под присмотром взрослых; детали уточнит команда.', 'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.': 'Свою еду и лакомства для котов оставляем за пределами кафе.', 'Wizyta wiąże się z obecnością sierści i alergenów, dlatego nie możemy zagwarantować bezpiecznych warunków dla osób z alergią. Jeśli objawy są łagodne, przed rezerwacją skonsultuj wizytę z lekarzem i poinformuj obsługę.': 'В кафе есть шерсть и аллергены, поэтому мы не можем гарантировать безопасные условия. Перед визитом проконсультируйтесь с врачом и предупредите команду.', 'Nie. Ze względów higienicznych i bezpieczeństwa kotów własne jedzenie oraz napoje zostawiamy poza lokalem. Na miejscu czeka menu kawiarni z opcjami wegetariańskimi.': 'Нет. Ради гигиены и безопасности котов свою еду и напитки оставляем снаружи. В кафе есть вегетарианские блюда.', 'Nie. Nawet spokojny pies lub kot może stresować naszych rezydentów. Wyjątek stanowią certyfikowane psy asystujące — prosimy o wcześniejszy kontakt.': 'Нет. Даже спокойное животное может вызвать стресс у жителей кафе. Исключение — сертифицированные собаки-поводыри; предупредите нас заранее.', 'W tygodniu zwykle wystarczy przyjść, ale rezerwacja daje pewność miejsca. W weekendy i podczas wydarzeń polecamy zarezerwować stolik z wyprzedzeniem.': 'В будни обычно можно прийти без записи, но бронь гарантирует место. На выходных и во время событий лучше записаться заранее.'
  },
  en: {
    'Przed wejściem do strefy kotów dezynfekujemy ręce.': 'Please sanitise your hands before entering the cat area.', 'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.': 'Let the cats choose contact — do not wake them or pick them up.', 'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.': 'Please take photos without flash and respect the cats’ calm.', 'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.': 'Children are welcome with continuous adult supervision; ask the team for details.', 'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.': 'Please leave your own food and cat treats outside the café.', 'Wizyta wiąże się z obecnością sierści i alergenów, dlatego nie możemy zagwarantować bezpiecznych warunków dla osób z alergią. Jeśli objawy są łagodne, przed rezerwacją skonsultuj wizytę z lekarzem i poinformuj obsługę.': 'The café contains fur and allergens, so we cannot guarantee safe conditions. Please consult your doctor and tell the team before booking.', 'Nie. Ze względów higienicznych i bezpieczeństwa kotów własne jedzenie oraz napoje zostawiamy poza lokalem. Na miejscu czeka menu kawiarni z opcjami wegetariańskimi.': 'No. For hygiene and cat safety, please leave your own food and drinks outside. Vegetarian options are available.', 'Nie. Nawet spokojny pies lub kot może stresować naszych rezydentów. Wyjątek stanowią certyfikowane psy asystujące — prosimy o wcześniejszy kontakt.': 'No. Even a calm animal can stress our residents. Certified assistance dogs are the exception; please contact us first.', 'W tygodniu zwykle wystarczy przyjść, ale rezerwacja daje pewność miejsca. W weekendy i podczas wydarzeń polecamy zarezerwować stolik z wyprzedzeniem.': 'You can usually walk in during the week, but a reservation guarantees a place. We recommend booking ahead for weekends and events.'
  },
};
const menuSlides = [
  { image: '/images/menu-latte.webp', alt: 'Kocie latte z maślanym ciasteczkiem', label: 'Kocie latte' },
  { image: '/images/menu-toast.webp', alt: 'Grzanka z kozim serem i pieczonym burakiem', label: 'Grzanka z kozim serem' },
  { image: '/images/menu-cheesecake.webp', alt: 'Sernik baskijski z owocami i matchą', label: 'Sernik baskijski' },
];
const catOfDay = {
  name: 'Pixel',
  slug: 'pixel',
  image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=88&w=1200&auto=format&fit=crop',
  pl: { label: 'Kot dnia', eyebrow: 'Poznaj go spokojnie', mood: 'Gotowy na spotkanie', activity: 'Dziś poluje na zabawkową myszkę i szuka osoby, która podaruje mu chwilę spokojnej uwagi.', button: 'Otwórz profil' },
  ru: { label: 'Кот дня', eyebrow: 'Познакомься с ним спокойно', mood: 'Готов к встрече', activity: 'Сегодня охотится на игрушечную мышку и ищет человека, который подарит ему немного спокойного внимания.', button: 'Открыть профиль' },
  en: { label: 'Cat of the day', eyebrow: 'Meet him at his own pace', mood: 'Ready to meet', activity: 'Today he is hunting a toy mouse and looking for someone to give him a little calm attention.', button: 'Open profile' },
};

export default function App() {
  const [chatOpen, setChatOpen] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [menuSlide, setMenuSlide] = useState(0);
  const [bookingOpen, setBookingOpen] = useState(false);
  const [supportOpen, setSupportOpen] = useState(false);
  const [language, setLanguage] = useState(() => window.localStorage.getItem('niebieski-kot-language') || 'pl');
  const [messages, setMessages] = useState([{ role: 'assistant', content: 'Cześć! 🐾 Zapytaj mnie o godziny, zasady, menu albo naszych rezydentów.' }]);
  const scrollRef = useRef(null);
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [messages, chatOpen]);
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;
    const timer = window.setInterval(() => setMenuSlide((slide) => (slide + 1) % menuSlides.length), 4500);
    return () => window.clearInterval(timer);
  }, []);
  useEffect(() => {
    document.documentElement.lang = language;
    const sourcePage = pageCopy.pl;
    const targetPage = pageCopy[language] || sourcePage;
    const pageMap = Object.fromEntries(Object.keys(sourcePage).map((key) => [sourcePage[key], targetPage[key]]));
    const targetCats = catTranslations[language] || {};
    const catMap = Object.fromEntries(cats.flatMap((cat) => Object.keys(cat).filter((key) => ['linkLabel', 'note', 'story'].includes(key)).map((key) => [cat[key], targetCats[cat.slug]?.[key] || cat[key]])));
    const map = { ...pageMap, ...catMap, ...(contentTranslations[language] || {}), ...(domTranslations[language] || {}), ...(extraTranslations[language] || {}), ...(detailTranslations[language] || {}) };
    if (!map) return undefined;
    const translate = () => {
      const walker = document.createTreeWalker(document.getElementById('top') || document.body, NodeFilter.SHOW_TEXT);
      const nodes = [];
      while (walker.nextNode()) nodes.push(walker.currentNode);
      nodes.forEach((node) => {
        if (!node.nodeValue.trim()) return;
        let value = node.nodeValue;
        Object.entries(map).forEach(([from, to]) => { value = value.replaceAll(from, to); });
        if (value !== node.nodeValue) node.nodeValue = value;
      });
    };
    const timer = window.setTimeout(translate, 0);
    const observer = new MutationObserver(translate);
    observer.observe(document.getElementById('top') || document.body, { childList: true, subtree: true });
    return () => { window.clearTimeout(timer); observer.disconnect(); };
  }, [language]);
  const closeBooking = useCallback(() => setBookingOpen(false), []);
  const closeSupport = useCallback(() => setSupportOpen(false), []);
  const copy = languageCopy[language] || languageCopy.pl;
  const page = pageCopy[language] || pageCopy.pl;
  const catOfDayCopy = catOfDay[language] || catOfDay.pl;
  const changeLanguage = (nextLanguage) => { window.localStorage.setItem('niebieski-kot-language', nextLanguage); window.location.reload(); };
  const scrollTo = (id) => { setMobileMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  const warsawNow = new Date(new Date().toLocaleString('en-US', { timeZone: 'Europe/Warsaw' }));
  const day = warsawNow.getDay();
  const hour = warsawNow.getHours();
  const isOpen = day !== 1 && hour >= (day === 0 || day === 6 ? 10 : 11) && hour < 20;
  const send = () => {
    const text = input.trim().slice(0, 200); if (!text || loading) return;
    setMessages((m) => [...m, { role: 'user', content: text }]); setInput(''); setLoading(true);
    window.setTimeout(() => {
      const q = text.toLowerCase(); let reply = 'Najlepiej opowiem Ci o godzinach, zasadach, menu lub kotach. Dane kontaktowe i rezerwacje pojawią się przed otwarciem.';
      if (q.includes('godzin') || q.includes('otwar')) reply = 'Wt–Pt zapraszamy 11:00–20:00, w weekend 10:00–20:00. Poniedziałek jest dniem odpoczynku kotów.';
      else if (q.includes('dziec') || q.includes('wiek')) reply = 'Zapraszamy dzieci od 8 lat. Goście w wieku 8–12 lat odwiedzają nas z dorosłym, a w weekend prosimy o rezerwację.';
      else if (q.includes('menu') || q.includes('kaw') || q.includes('ciast') || q.includes('jedz') || q.includes('głod')) reply = 'Kawy kosztują 10–18 zł, napoje bez kawy 14–18 zł, ciasta 17–19 zł, a śniadania i lekkie dania 19–28 zł. Mamy opcje wegetariańskie i mleko roślinne bez dopłaty.';
      else if (q.includes('kot') || q.includes('adopc')) reply = 'Nasi rezydenci mają własne charaktery i spokojne miejsca do odpoczynku. Wspieramy też lokalne działania adopcyjne.';
      else if (q.includes('adres') || q.includes('gdzie') || q.includes('rezerw')) reply = 'Koncepcyjny lokal mieści się przy ul. Krakowskiej 32 w Opolu. Rezerwujemy stoliki na 90 minut; w weekend warto zrobić to wcześniej.';
      setMessages((m) => [...m, { role: 'assistant', content: reply }]); setLoading(false);
    }, 650);
  };
  const links = [['about', copy.nav[0]], ['cats', copy.nav[1]], ['menu', copy.nav[2]], ['rules', copy.nav[3]], ['events', copy.nav[4]], ['support', copy.nav[5]], ['visit', copy.nav[6]]];

  return <div className="min-h-screen overflow-x-hidden bg-[#f7f8f4] text-slate-950 selection:bg-sky-200">
    <nav className="fixed inset-x-0 top-0 z-40 border-b border-white/50 bg-[#f7f8f4]/85 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-8">
        <button onClick={() => scrollTo('top')} className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-sky-500 text-white"><Cat size={19}/></span><span className="text-lg font-extrabold tracking-tight">Niebieski Kot<span className="text-sky-500">.</span></span></button>
        <div className="hidden items-center gap-7 md:flex">{links.map(([id,label]) => id === 'menu' ? <a key={id} href="/menu" className="text-sm font-semibold text-slate-600 transition hover:text-slate-950">{label}</a> : <button key={id} onClick={() => scrollTo(id)} className="text-sm font-semibold text-slate-600 transition hover:text-slate-950">{label}</button>)}</div>
        <div className="flex items-center gap-2"><label className="flex items-center gap-1.5 rounded-full border border-slate-200 bg-white/70 px-3 py-2 text-xs font-bold text-slate-600"><Globe2 size={15} className="text-sky-500"/><span className="sr-only">Wybierz język</span><select value={language} onChange={(event) => changeLanguage(event.target.value)} aria-label="Wybierz język" className="cursor-pointer bg-transparent outline-none"><option value="pl">PL</option><option value="ru">RU</option><option value="en">EN</option></select></label><button onClick={() => setChatOpen(true)} className="hidden items-center gap-2 rounded-full bg-slate-950 px-5 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-sky-600 md:flex">{copy.ask} <ArrowRight size={15}/></button></div>
        <button onClick={() => setMobileMenu(!mobileMenu)} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 md:hidden" aria-label="Menu">{mobileMenu ? <X/> : <Menu/>}</button>
      </div>
      {mobileMenu && <div className="border-t border-slate-200 bg-[#f7f8f4] px-5 py-5 md:hidden">{links.map(([id,label]) => id === 'menu' ? <a key={id} href="/menu" className="block w-full border-b border-slate-200 py-3 text-left font-bold">{label}</a> : <button key={id} onClick={() => scrollTo(id)} className="block w-full border-b border-slate-200 py-3 text-left font-bold">{label}</button>)}</div>}
    </nav>

    <main id="top" className="flex flex-col">
      <header className="mx-auto grid min-h-[780px] max-w-6xl items-center gap-12 px-5 pb-20 pt-32 sm:px-8 lg:grid-cols-[1.05fr_.95fr]">
        <div className="relative z-10">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white px-3.5 py-2 text-xs font-extrabold uppercase tracking-[.16em] text-sky-700 shadow-sm"><span className={`h-2 w-2 rounded-full ${isOpen ? 'animate-pulse bg-emerald-500' : 'bg-slate-400'}`}/>{isOpen ? page.open : day === 1 ? page.monday : page.today}</div>
          <p className="mb-4 text-sm font-extrabold uppercase tracking-[.22em] text-sky-600">{copy.eyebrow}</p>
          <h1 className="text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-7xl lg:text-[5.25rem]">{copy.hero}</h1>
          <p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-600">{copy.intro}</p>
          <div className="mt-9 flex flex-wrap gap-3"><button onClick={() => setBookingOpen(true)} className="flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 font-bold text-white shadow-xl transition hover:-translate-y-1 hover:bg-sky-600">{copy.booking} <ArrowRight size={18}/></button><button onClick={() => scrollTo('cats')} className="rounded-full border border-slate-300 bg-white px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">{copy.cats}</button></div>
          <div className="mt-12 flex flex-wrap gap-7 text-sm font-semibold text-slate-500"><span className="flex items-center gap-2"><Heart size={17} className="text-sky-500"/> {page.adopt}</span><span className="flex items-center gap-2"><Coffee size={17} className="text-sky-500"/> {page.coffee}</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-[520px]"><div className="absolute -left-8 -top-8 h-40 w-40 rounded-full bg-sky-200/60 blur-2xl"/><div className="relative aspect-[4/5] overflow-hidden rounded-[3rem] bg-sky-100 shadow-2xl"><img src="https://images.unsplash.com/photo-1543852786-1cf6624b9987?q=85&w=1200&auto=format&fit=crop" alt={page.homeTitle} className="h-full w-full object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-3xl border border-white/40 bg-white/80 p-5 backdrop-blur-xl"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-sky-500 text-white"><PawPrint size={21}/></span><div><p className="font-extrabold">{page.homeTitle}</p><p className="text-sm text-slate-600">{page.homeText}</p></div></div></div></div><div className="absolute -right-4 top-16 rotate-6 rounded-2xl bg-amber-300 px-4 py-3 text-sm font-black shadow-lg sm:-right-8">zero pośpiechu ✦</div></div>
      </header>

      <section id="about" className="bg-slate-950 py-24 text-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-400">Nasza idea</span><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight sm:text-5xl">Dobre rzeczy dzieją się wolniej.</h2></div><div className="grid gap-5 sm:grid-cols-2"><p className="text-lg leading-relaxed text-slate-300">Tworzymy kameralną kawiarnię, w której dobrostan kotów jest równie ważny jak smak espresso.</p><p className="text-lg leading-relaxed text-slate-300">Każdy rezydent ma własną historię, charakter i przestrzeń. Ty dostajesz chwilę oddechu — on wybór, czy chce dołączyć.</p></div></div></section>

      <section id="cats" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Nasi gospodarze</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Poznaj ekipę.</h2></div><p className="max-w-md text-slate-600">Każdy inny. Każdy u siebie. Pixel szuka domu, Luna i Mochi są stałymi gospodarzami.</p></div><div className="grid gap-5 md:grid-cols-3">{cats.map((cat,i) => <article key={cat.name} className={`group overflow-hidden rounded-[2rem] bg-white shadow-sm ${i === 1 ? 'md:translate-y-8' : ''}`}><div className="aspect-[4/5] overflow-hidden"><img src={cat.image} alt={`Kot ${cat.name}`} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">{cat.name}</h3><p className="mt-1 text-sm font-semibold text-sky-600">{cat.note}</p></div><PawPrint className="text-sky-400"/></div><p className="mt-4 text-sm leading-relaxed text-slate-600">{cat.story}</p><a href={`/koty/${cat.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-sky-600 transition hover:gap-3 hover:text-sky-700">{cat.linkLabel} <ArrowRight size={16}/></a></div></article>)}</div></section>

      <section id="menu" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="relative overflow-hidden rounded-[3rem] bg-sky-500 px-7 py-10 text-white sm:px-12 sm:py-12"><div className="absolute -left-12 -top-16 text-white/10"><Coffee size={220}/></div><div className="relative grid items-center gap-10 lg:grid-cols-[1.05fr_.75fr]"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-100">Jedzenie i napoje</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Kocia karta ma własne miejsce.</h2><p className="mt-5 max-w-xl leading-relaxed text-sky-50">Kawy specialty, śniadania, lekkie dania i domowe słodkości — teraz w przejrzystym menu z cenami.</p><a href="/menu" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-extrabold text-sky-600 transition hover:-translate-y-1">Otwórz pełne menu <ArrowRight size={18}/></a></div><div className="mx-auto w-full max-w-sm"><div className="relative aspect-[4/5] overflow-hidden rounded-[2.25rem] bg-sky-300 shadow-2xl ring-1 ring-white/30">{menuSlides.map((slide, index) => <img key={slide.image} src={slide.image} alt={index === menuSlide ? slide.alt : ''} aria-hidden={index !== menuSlide} loading="lazy" className={`absolute inset-0 h-full w-full object-cover transition duration-700 ${index === menuSlide ? 'scale-100 opacity-100' : 'scale-105 opacity-0'}`}/>) }<div className="absolute inset-x-4 bottom-4 flex items-center justify-between gap-3 rounded-2xl bg-slate-950/75 p-3 backdrop-blur-md"><button type="button" onClick={() => setMenuSlide((slide) => (slide - 1 + menuSlides.length) % menuSlides.length)} aria-label="Poprzednie zdjęcie" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 transition hover:bg-white/25"><ChevronLeft size={18}/></button><p className="text-center text-sm font-extrabold">{menuSlides[menuSlide].label}</p><button type="button" onClick={() => setMenuSlide((slide) => (slide + 1) % menuSlides.length)} aria-label="Następne zdjęcie" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 transition hover:bg-white/25"><ChevronRight size={18}/></button></div></div><div className="mt-4 flex justify-center gap-2">{menuSlides.map((slide, index) => <button key={slide.image} type="button" onClick={() => setMenuSlide(index)} aria-label={`Pokaż zdjęcie ${index + 1}: ${slide.label}`} aria-current={index === menuSlide} className={`h-2 rounded-full transition-all ${index === menuSlide ? 'w-7 bg-white' : 'w-2 bg-white/45 hover:bg-white/70'}`}/>)}</div></div></div></div></section>

      <section id="rules" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Koci savoir-vivre</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Kilka zasad.<br/>Dużo spokoju.</h2><p className="mt-5 max-w-md leading-relaxed text-slate-600">To dom naszych rezydentów. Proste reguły sprawiają, że wszystkim — na dwóch i czterech łapach — jest tu dobrze.</p><ul className="mt-8 space-y-3">{rules.map((rule) => <li key={rule} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-sky-100 text-sky-600"><Check size={14}/></span><span className="text-sm font-semibold leading-relaxed text-slate-700">{rule}</span></li>)}</ul></div><div><div className="mb-5 flex items-center justify-between"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">FAQ pierwszej wizyty</span><h3 className="mt-2 text-3xl font-black tracking-tight">Dobrze wiedzieć przed przyjściem.</h3></div><ShieldCheck className="hidden text-sky-500 sm:block" size={30}/></div><div className="space-y-3">{faqItems.map(({ question, answer }) => <details key={question} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-extrabold text-slate-800 marker:hidden"><span>{question}</span><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-sky-100 text-sky-600 text-xl leading-none transition group-open:rotate-45">+</span></summary><p className="pt-4 text-sm leading-relaxed text-slate-600">{answer}</p></details>)}</div></div></div></section>

      <section id="visit" className="mx-auto max-w-6xl px-5 pb-24 pt-10 sm:px-8"><div className="grid overflow-hidden rounded-[3rem] bg-white shadow-xl lg:grid-cols-[1fr_.9fr]"><div className="p-7 sm:p-12"><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Zanim wpadniesz</span><h2 className="mt-3 text-4xl font-black tracking-tight">Zaplanuj miękkie lądowanie.</h2><div className="mt-9 space-y-5"><Info icon={Clock3} title="Wt–Pt 11:00–20:00 · Sob–Nd 10:00–20:00" text="W poniedziałki lokal jest zamknięty — to dzień ciszy dla kotów."/><Info icon={MapPin} title="ul. Krakowska 32, 45-075 Opole" text="5 minut spacerem od opolskiego Rynku · adres koncepcyjny."/><Info icon={CalendarDays} title="Stoliki na 90 minut" text="W weekend rezerwacja zalecana. Dzieci od 8 lat, zawsze pod opieką dorosłego."/></div><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => setBookingOpen(true)} className="flex items-center gap-2 rounded-full bg-sky-500 px-6 py-3.5 font-bold text-white transition hover:-translate-y-1 hover:bg-sky-600">Zarezerwuj stolik <CalendarDays size={18}/></button><button onClick={() => setChatOpen(true)} className="flex items-center gap-2 rounded-full border border-slate-300 px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">Zapytaj asystenta <MessageCircle size={18}/></button><a href="https://www.openstreetmap.org/search?query=Krakowska%2032%20Opole" target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-slate-300 px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">Pokaż mapę <MapPin size={18}/></a></div></div><div className="relative min-h-[380px]"><img src="https://images.unsplash.com/photo-1511081692775-05d0f180a065?q=85&w=1200&auto=format&fit=crop" alt="Przytulne wnętrze kawiarni" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/35 to-transparent"/></div></div></section>
      <section id="support" className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><span className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[.2em] text-sky-400"><HeartHandshake size={17}/> Dla naszych kotów</span><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight sm:text-5xl">Mały gest.<br/>Dużo spokoju.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-slate-300">Opieka weterynaryjna, karma i spokojne kryjówki są ważniejsze niż kolejna zabawka. Wybierz sposób, w jaki chcesz dołożyć swoją cegiełkę.</p><button type="button" onClick={() => setSupportOpen(true)} className="mt-8 inline-flex items-center gap-2 rounded-full bg-amber-300 px-6 py-3.5 font-extrabold text-amber-950 transition hover:-translate-y-1 hover:bg-amber-200">Wesprzyj koty <HeartHandshake size={18}/></button></div><div className="grid gap-3 sm:grid-cols-3">{[['Wirtualna kawa','15 zł','na codzienną opiekę'],['Miska na dziś','35 zł','na karmę i żwirek'],['Wsparcie leczenia','100 zł','na badania i wizyty']].map(([title, amount, text]) => <button key={title} type="button" onClick={() => setSupportOpen(true)} className="rounded-3xl border border-white/10 bg-white/10 p-5 text-left transition hover:-translate-y-1 hover:bg-white/15"><Coffee className="text-amber-300" size={20}/><p className="mt-6 text-sm font-bold text-slate-300">{title}</p><p className="mt-1 text-3xl font-black">{amount}</p><p className="mt-2 text-xs leading-relaxed text-slate-400">{text}</p></button>)}</div></div><div className="mt-12 grid gap-5 rounded-[2.5rem] bg-white p-7 text-slate-950 sm:p-9 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[.18em] text-sky-600"><ShoppingBasket size={17}/> Lista potrzeb</p><h3 className="mt-3 text-3xl font-black">Co przyda się najbardziej?</h3><p className="mt-3 leading-relaxed text-slate-600">Rzeczy można przynieść po wcześniejszym kontakcie z obsługą. Najpierw sprawdzimy, czego aktualnie potrzebują koty.</p></div><ul className="grid gap-2 sm:grid-cols-2">{['mokra karma dobrej jakości','żwirek bentonitowy bez zapachu','polarowe koce i ręczniki','transportery w dobrym stanie','preparaty na pchły i kleszcze','środki do bezpiecznego sprzątania'].map((item) => <li key={item} className="flex items-center gap-3 rounded-2xl bg-sky-50 px-4 py-3 text-sm font-bold text-slate-700"><Check size={16} className="shrink-0 text-emerald-500"/>{item}</li>)}</ul></div></div></section>
      <section id="events" className="bg-sky-50 py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">W kalendarzu kociej kawiarni</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Wydarzenia, na które chce się wracać.</h2></div><p className="max-w-md text-slate-600">Małe spotkania w spokojnym rytmie. Liczba miejsc jest ograniczona, dlatego warto zapisać się wcześniej.</p></div><div className="grid gap-4 md:grid-cols-2">{events.map(({ icon: Icon, tag, title, text, meta }) => <article key={title} className="group rounded-[2rem] border border-sky-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg sm:p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-100 text-sky-600"><Icon size={22}/></span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-extrabold text-amber-800">{tag}</span></div><h3 className="mt-6 text-2xl font-black">{title}</h3><p className="mt-3 min-h-12 text-sm leading-relaxed text-slate-600">{text}</p><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="text-xs font-extrabold text-slate-500">{meta}</span><button type="button" onClick={() => setBookingOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white transition hover:bg-sky-600">Zapisz się <ArrowRight size={15}/></button></div></article>)}</div></div></section>

      <section className="mx-auto max-w-6xl px-5 pb-24 sm:px-8"><div className="grid overflow-hidden rounded-[3rem] bg-amber-300 lg:grid-cols-[.85fr_1.15fr]"><div className="relative min-h-[320px]"><img src={catOfDay.image} alt={`${catOfDayCopy.label} ${catOfDay.name}`} loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/55 to-transparent"/><span className="absolute bottom-6 left-6 rounded-full bg-white/90 px-4 py-2 text-sm font-black text-slate-950">{catOfDayCopy.label}</span></div><div className="p-7 sm:p-12"><span className="text-sm font-extrabold uppercase tracking-[.2em] text-amber-900">{catOfDayCopy.eyebrow}</span><h2 className="mt-3 text-5xl font-black tracking-tight">{catOfDay.name}.</h2><p className="mt-4 inline-flex rounded-full bg-white/70 px-4 py-2 text-sm font-extrabold text-amber-950">{catOfDayCopy.mood}</p><p className="mt-6 max-w-lg text-lg leading-relaxed text-amber-950/80">{catOfDayCopy.activity}</p><a href={`/koty/${catOfDay.slug}`} className="mt-8 inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 font-extrabold text-white transition hover:-translate-y-1 hover:bg-sky-600">{catOfDayCopy.button} {catOfDay.name} <ArrowRight size={18}/></a></div></div></section>

    </main>

    <footer className="border-t border-slate-200 bg-white py-10"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-5 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div className="flex items-center gap-2 font-extrabold"><Cat className="text-sky-500"/> Niebieski Kot.</div><div className="text-sm text-slate-500"><p>ul. Krakowska 32 · Opole · czesc@niebieskikot-opole.pl</p><p className="mt-1 text-xs">Projekt koncepcyjny — adres, kontakt i bohaterowie są demonstracyjne.</p></div><a href="https://www.instagram.com/niebieskikot.opole" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-bold hover:text-sky-600"><Instagram size={18}/> @niebieskikot.opole</a></div></footer>

    <div className="fixed bottom-5 right-5 z-50">{chatOpen && <div className="mb-3 flex h-[min(520px,calc(100vh-110px))] w-[calc(100vw-40px)] max-w-[370px] flex-col overflow-hidden rounded-[2rem] border border-sky-100 bg-white/95 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between bg-slate-950 px-5 py-4 text-white"><div><b className="block text-sm">Niebieski Asystent</b><span className="mt-0.5 flex items-center gap-1 text-[10px] text-slate-300"><ShieldCheck size={10}/> szybkie odpowiedzi</span></div><button onClick={() => setChatOpen(false)} aria-label="Zamknij czat" className="rounded-full p-2 hover:bg-white/10"><X size={18}/></button></div><div ref={scrollRef} className="flex-1 space-y-4 overflow-y-auto p-5">{messages.map((m,i) => <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : ''}`}><div className={`max-w-[86%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${m.role === 'user' ? 'rounded-br-sm bg-sky-500 text-white' : 'rounded-bl-sm bg-slate-100'}`}>{m.content}</div></div>)}{loading && <div className="w-fit rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-400">Piszę…</div>}</div><div className="flex gap-2 border-t p-3"><input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} maxLength={200} aria-label="Wiadomość do asystenta" placeholder="Napisz wiadomość…" className="min-w-0 flex-1 rounded-full bg-slate-100 px-4 text-sm outline-none focus:ring-2 focus:ring-sky-400"/><button onClick={send} disabled={loading || !input.trim()} aria-label="Wyślij wiadomość" className="grid h-11 w-11 place-items-center rounded-full bg-sky-500 text-white disabled:opacity-40"><Send size={17}/></button></div></div>}<button onClick={() => setChatOpen(!chatOpen)} aria-label={chatOpen ? 'Zamknij czat' : 'Otwórz czat'} className="ml-auto grid h-14 w-14 place-items-center rounded-full bg-sky-500 text-white shadow-xl shadow-sky-500/30 transition hover:scale-105">{chatOpen ? <X/> : <MessageCircle/>}</button></div>
    <BookingModal open={bookingOpen} onClose={closeBooking}/><SupportModal open={supportOpen} onClose={closeSupport}/>
  </div>;
}

function Info({ icon: Icon, title, text }) { return <div className="flex gap-4"><Icon className="mt-1 shrink-0 text-sky-500"/><div><p className="font-extrabold">{title}</p><p className="text-sm text-slate-500">{text}</p></div></div>; }
