import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, CalendarDays, Cat, Check, ChevronLeft, ChevronRight, Clock3, Coffee, Globe2, Heart, HeartHandshake, Instagram, MapPin, Menu, MessageCircle, PawPrint, Send, ShieldCheck, ShoppingBasket, X } from 'lucide-react';
import BookingModal from './BookingModal.jsx';
import SupportModal from './SupportModal.jsx';

const cats = [
  { name: 'Luna', linkLabel: 'Poznaj Lunę', note: '4 lata · spokojna obserwatorka', story: 'Trafiła do nas po przeprowadzce opiekunów. Najchętniej siedzi przy oknie i sama wybiera moment na głaskanie.', image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=85&w=900&auto=format&fit=crop', slug: 'luna' },
  { name: 'Mochi', linkLabel: 'Poznaj Mochiego', note: '6 lat · mistrz drzemek', story: 'Łagodny kocur znaleziony na działkach. Kocha miękkie koce, spokojne rozmowy i ludzi z książką na kolanach.', image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=85&w=900&auto=format&fit=crop', slug: 'mochi' },
  { name: 'Pixel', linkLabel: 'Poznaj Pixela', note: '2 lata · pierwszy do zabawy', story: 'Najmłodszy w ekipie i kandydat do adopcji. Wędkę wypatrzy z drugiego końca sali, a potem zasypia pod stolikiem.', image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=85&w=900&auto=format&fit=crop', slug: 'pixel' },
];
const rules = [
  'Przed wejściem do strefy kotów dezynfekujemy ręce.',
  'Pozwalamy kotom decydować o kontakcie — nie budzimy ich i nie bierzemy na ręce.',
  'Zdjęcia robimy bez lampy błyskowej, z szacunkiem dla kociego spokoju.',
  'Dzieci zapraszamy pod stałą opieką dorosłych; szczegóły potwierdzi obsługa.',
  'Własne jedzenie oraz smakołyki dla kotów zostawiamy poza lokalem.',
];
const faqItems = [
  { question: 'Czy można przyjść z dziećmi?', answer: 'Tak. Zapraszamy dzieci od 8 lat, zawsze pod opieką dorosłego. Prosimy, aby dzieci nie biegały i pozwalały kotom samodzielnie decydować o kontakcie.' },
  { question: 'Mam alergię na koty — czy mogę odwiedzić kawiarnię?', answer: 'Wizyta wiąże się z obecnością sierści i alergenów, dlatego nie możemy zagwarantować bezpiecznych warunków dla osób z alergią. Jeśli objawy są łagodne, przed rezerwacją skonsultuj wizytę z lekarzem i poinformuj obsługę.' },
  { question: 'Czy można przynieść własne jedzenie?', answer: 'Nie. Ze względów higienicznych i bezpieczeństwa kotów własne jedzenie oraz napoje zostawiamy poza lokalem. Na miejscu czeka menu kawiarni z opcjami wegetariańskimi.' },
  { question: 'Czy można przyjść z własnym zwierzęciem?', answer: 'Nie. Nawet spokojny pies lub kot może stresować naszych rezydentów. Wyjątek stanowią certyfikowane psy asystujące — prosimy o wcześniejszy kontakt.' },
  { question: 'Czy trzeba rezerwować miejsce?', answer: 'W tygodniu zwykle wystarczy przyjść, ale rezerwacja daje pewność miejsca. W weekendy i podczas wydarzeń polecamy zarezerwować stolik z wyprzedzeniem.' },
];
const events = [
  { icon: Heart, tag: 'Каждое воскресенье', title: 'Йога с котами', text: 'Мягкая практика для начинающих, тихая музыка и свободно гуляющие по залу коты.', meta: '10:00 · 60 минут · 45 zł' },
  { icon: Coffee, tag: 'Каждую пятницу', title: 'Вечер настольных игр', text: 'Небольшие компании, уютные игры и горячий напиток из нашего меню.', meta: '18:00 · 90 минут · 25 zł' },
  { icon: Cat, tag: 'Две субботы в месяц', title: 'Чтения и мастер-классы', text: 'Истории о животных, творческие занятия и спокойный формат для всей семьи.', meta: '12:00 · 75 минут · от 20 zł' },
  { icon: PawPrint, tag: 'Первое воскресенье месяца', title: 'День усыновления', text: 'Знакомство с котами, консультации волонтёров и помощь в подготовке к ответственному дому.', meta: 'Без входного взноса · регистрация обязательна' },
];
const languageCopy = {
  pl: { nav: ['O nas', 'Koty', 'Menu', 'Zasady', 'Wydarzenia', 'Wesprzyj', 'Wizyta'], ask: 'Zapytaj nas', booking: 'Zarezerwuj stolik', cats: 'Poznaj koty', eyebrow: 'Kocia kawiarnia · Opole', hero: 'Zwolnij. Kawa stygnie, koty nie.', intro: 'Spokojne miejsce na dobrą kawę, miękki fotel i spotkanie z kotami, które naprawdę nadają temu miejscu rytm.' },
  ru: { nav: ['О нас', 'Коты', 'Меню', 'Правила', 'События', 'Поддержать', 'Визит'], ask: 'Спросить нас', booking: 'Забронировать столик', cats: 'Познакомиться с котами', eyebrow: 'Котокафе · Ополе', hero: 'Замедлись. Кофе остывает, коты — нет.', intro: 'Уютное место для хорошего кофе, мягкого кресла и встречи с котами, которые задают этому месту свой ритм.' },
  en: { nav: ['About', 'Cats', 'Menu', 'Rules', 'Events', 'Support', 'Visit'], ask: 'Ask us', booking: 'Book a table', cats: 'Meet the cats', eyebrow: 'Cat café · Opole', hero: 'Slow down. Coffee cools, cats don’t.', intro: 'A calm place for good coffee, a soft chair and time with cats who give this café its own rhythm.' },
};
const menuSlides = [
  { image: '/images/menu-latte.webp', alt: 'Kocie latte z maślanym ciasteczkiem', label: 'Kocie latte' },
  { image: '/images/menu-toast.webp', alt: 'Grzanka z kozim serem i pieczonym burakiem', label: 'Grzanka z kozim serem' },
  { image: '/images/menu-cheesecake.webp', alt: 'Sernik baskijski z owocami i matchą', label: 'Sernik baskijski' },
];

export default function App() {
  const [chatOpen, setChatOpen] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [menuSlide, setMenuSlide] = useState(0);
  const [bookingOpen, setBookingOpen] = useState(false);
  const [supportOpen, setSupportOpen] = useState(false);
  const [language, setLanguage] = useState(() => window.localStorage.getItem('niebieski-kot-language') || 'pl');
  const [messages, setMessages] = useState([{ role: 'assistant', content: 'Cześć! 🐾 Zapytaj mnie o godziny, zasady, menu albo naszych rezydentów.' }]);
  const scrollRef = useRef(null);
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [messages, chatOpen]);
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;
    const timer = window.setInterval(() => setMenuSlide((slide) => (slide + 1) % menuSlides.length), 4500);
    return () => window.clearInterval(timer);
  }, []);
  const closeBooking = useCallback(() => setBookingOpen(false), []);
  const closeSupport = useCallback(() => setSupportOpen(false), []);
  const copy = languageCopy[language] || languageCopy.pl;
  const changeLanguage = (nextLanguage) => { setLanguage(nextLanguage); window.localStorage.setItem('niebieski-kot-language', nextLanguage); document.documentElement.lang = nextLanguage; };
  const scrollTo = (id) => { setMobileMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  const warsawNow = new Date(new Date().toLocaleString('en-US', { timeZone: 'Europe/Warsaw' }));
  const day = warsawNow.getDay();
  const hour = warsawNow.getHours();
  const isOpen = day !== 1 && hour >= (day === 0 || day === 6 ? 10 : 11) && hour < 20;
  const send = () => {
    const text = input.trim().slice(0, 200); if (!text || loading) return;
    setMessages((m) => [...m, { role: 'user', content: text }]); setInput(''); setLoading(true);
    window.setTimeout(() => {
      const q = text.toLowerCase(); let reply = 'Najlepiej opowiem Ci o godzinach, zasadach, menu lub kotach. Dane kontaktowe i rezerwacje pojawią się przed otwarciem.';
      if (q.includes('godzin') || q.includes('otwar')) reply = 'Wt–Pt zapraszamy 11:00–20:00, w weekend 10:00–20:00. Poniedziałek jest dniem odpoczynku kotów.';
      else if (q.includes('dziec') || q.includes('wiek')) reply = 'Zapraszamy dzieci od 8 lat. Goście w wieku 8–12 lat odwiedzają nas z dorosłym, a w weekend prosimy o rezerwację.';
      else if (q.includes('menu') || q.includes('kaw') || q.includes('ciast') || q.includes('jedz') || q.includes('głod')) reply = 'Kawy kosztują 10–18 zł, napoje bez kawy 14–18 zł, ciasta 17–19 zł, a śniadania i lekkie dania 19–28 zł. Mamy opcje wegetariańskie i mleko roślinne bez dopłaty.';
      else if (q.includes('kot') || q.includes('adopc')) reply = 'Nasi rezydenci mają własne charaktery i spokojne miejsca do odpoczynku. Wspieramy też lokalne działania adopcyjne.';
      else if (q.includes('adres') || q.includes('gdzie') || q.includes('rezerw')) reply = 'Koncepcyjny lokal mieści się przy ul. Krakowskiej 32 w Opolu. Rezerwujemy stoliki na 90 minut; w weekend warto zrobić to wcześniej.';
      setMessages((m) => [...m, { role: 'assistant', content: reply }]); setLoading(false);
    }, 650);
  };
  const links = [['about', copy.nav[0]], ['cats', copy.nav[1]], ['menu', copy.nav[2]], ['rules', copy.nav[3]], ['events', copy.nav[4]], ['support', copy.nav[5]], ['visit', copy.nav[6]]];

  return <div className="min-h-screen overflow-x-hidden bg-[#f7f8f4] text-slate-950 selection:bg-sky-200">
    <nav className="fixed inset-x-0 top-0 z-40 border-b border-white/50 bg-[#f7f8f4]/85 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-8">
        <button onClick={() => scrollTo('top')} className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-sky-500 text-white"><Cat size={19}/></span><span className="text-lg font-extrabold tracking-tight">Niebieski Kot<span className="text-sky-500">.</span></span></button>
        <div className="hidden items-center gap-7 md:flex">{links.map(([id,label]) => id === 'menu' ? <a key={id} href="/menu" className="text-sm font-semibold text-slate-600 transition hover:text-slate-950">{label}</a> : <button key={id} onClick={() => scrollTo(id)} className="text-sm font-semibold text-slate-600 transition hover:text-slate-950">{label}</button>)}</div>
        <div className="flex items-center gap-2"><label className="flex items-center gap-1.5 rounded-full border border-slate-200 bg-white/70 px-3 py-2 text-xs font-bold text-slate-600"><Globe2 size={15} className="text-sky-500"/><span className="sr-only">Выбрать язык</span><select value={language} onChange={(event) => changeLanguage(event.target.value)} aria-label="Выбрать язык" className="cursor-pointer bg-transparent outline-none"><option value="pl">PL</option><option value="ru">RU</option><option value="en">EN</option></select></label><button onClick={() => setChatOpen(true)} className="hidden items-center gap-2 rounded-full bg-slate-950 px-5 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-sky-600 md:flex">{copy.ask} <ArrowRight size={15}/></button></div>
        <button onClick={() => setMobileMenu(!mobileMenu)} className="grid h-11 w-11 place-items-center rounded-full border border-slate-200 md:hidden" aria-label="Menu">{mobileMenu ? <X/> : <Menu/>}</button>
      </div>
      {mobileMenu && <div className="border-t border-slate-200 bg-[#f7f8f4] px-5 py-5 md:hidden">{links.map(([id,label]) => id === 'menu' ? <a key={id} href="/menu" className="block w-full border-b border-slate-200 py-3 text-left font-bold">{label}</a> : <button key={id} onClick={() => scrollTo(id)} className="block w-full border-b border-slate-200 py-3 text-left font-bold">{label}</button>)}</div>}
    </nav>

    <main id="top">
      <header className="mx-auto grid min-h-[780px] max-w-6xl items-center gap-12 px-5 pb-20 pt-32 sm:px-8 lg:grid-cols-[1.05fr_.95fr]">
        <div className="relative z-10">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white px-3.5 py-2 text-xs font-extrabold uppercase tracking-[.16em] text-sky-700 shadow-sm"><span className={`h-2 w-2 rounded-full ${isOpen ? 'animate-pulse bg-emerald-500' : 'bg-slate-400'}`}/>{isOpen ? 'Otwarte teraz · do 20:00' : day === 1 ? 'Poniedziałek · koty odpoczywają' : 'Dziś od 11:00'}</div>
          <p className="mb-4 text-sm font-extrabold uppercase tracking-[.22em] text-sky-600">{copy.eyebrow}</p>
          <h1 className="text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-7xl lg:text-[5.25rem]">{copy.hero}</h1>
          <p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-600">{copy.intro}</p>
          <div className="mt-9 flex flex-wrap gap-3"><button onClick={() => setBookingOpen(true)} className="flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 font-bold text-white shadow-xl transition hover:-translate-y-1 hover:bg-sky-600">{copy.booking} <ArrowRight size={18}/></button><button onClick={() => scrollTo('cats')} className="rounded-full border border-slate-300 bg-white px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">{copy.cats}</button></div>
          <div className="mt-12 flex flex-wrap gap-7 text-sm font-semibold text-slate-500"><span className="flex items-center gap-2"><Heart size={17} className="text-sky-500"/> Wspieramy adopcje</span><span className="flex items-center gap-2"><Coffee size={17} className="text-sky-500"/> Specialty coffee</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-[520px]"><div className="absolute -left-8 -top-8 h-40 w-40 rounded-full bg-sky-200/60 blur-2xl"/><div className="relative aspect-[4/5] overflow-hidden rounded-[3rem] bg-sky-100 shadow-2xl"><img src="https://images.unsplash.com/photo-1543852786-1cf6624b9987?q=85&w=1200&auto=format&fit=crop" alt="Kot odpoczywający w kawiarni" className="h-full w-full object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-3xl border border-white/40 bg-white/80 p-5 backdrop-blur-xl"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-sky-500 text-white"><PawPrint size={21}/></span><div><p className="font-extrabold">Tu kot wybiera Ciebie</p><p className="text-sm text-slate-600">Usiądź wygodnie i daj mu chwilę.</p></div></div></div></div><div className="absolute -right-4 top-16 rotate-6 rounded-2xl bg-amber-300 px-4 py-3 text-sm font-black shadow-lg sm:-right-8">zero pośpiechu ✦</div></div>
      </header>

      <section id="about" className="bg-slate-950 py-24 text-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-400">Nasza idea</span><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight sm:text-5xl">Dobre rzeczy dzieją się wolniej.</h2></div><div className="grid gap-5 sm:grid-cols-2"><p className="text-lg leading-relaxed text-slate-300">Tworzymy kameralną kawiarnię, w której dobrostan kotów jest równie ważny jak smak espresso.</p><p className="text-lg leading-relaxed text-slate-300">Każdy rezydent ma własną historię, charakter i przestrzeń. Ty dostajesz chwilę oddechu — on wybór, czy chce dołączyć.</p></div></div></section>

      <section id="cats" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Nasi gospodarze</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Poznaj ekipę.</h2></div><p className="max-w-md text-slate-600">Każdy inny. Każdy u siebie. Pixel szuka domu, Luna i Mochi są stałymi gospodarzami.</p></div><div className="grid gap-5 md:grid-cols-3">{cats.map((cat,i) => <article key={cat.name} className={`group overflow-hidden rounded-[2rem] bg-white shadow-sm ${i === 1 ? 'md:translate-y-8' : ''}`}><div className="aspect-[4/5] overflow-hidden"><img src={cat.image} alt={`Kot ${cat.name}`} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">{cat.name}</h3><p className="mt-1 text-sm font-semibold text-sky-600">{cat.note}</p></div><PawPrint className="text-sky-400"/></div><p className="mt-4 text-sm leading-relaxed text-slate-600">{cat.story}</p><a href={`/koty/${cat.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-sky-600 transition hover:gap-3 hover:text-sky-700">{cat.linkLabel} <ArrowRight size={16}/></a></div></article>)}</div></section>

      <section id="menu" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="relative overflow-hidden rounded-[3rem] bg-sky-500 px-7 py-10 text-white sm:px-12 sm:py-12"><div className="absolute -left-12 -top-16 text-white/10"><Coffee size={220}/></div><div className="relative grid items-center gap-10 lg:grid-cols-[1.05fr_.75fr]"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-100">Jedzenie i napoje</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Kocia karta ma własne miejsce.</h2><p className="mt-5 max-w-xl leading-relaxed text-sky-50">Kawy specialty, śniadania, lekkie dania i domowe słodkości — teraz w przejrzystym menu z cenami.</p><a href="/menu" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-extrabold text-sky-600 transition hover:-translate-y-1">Otwórz pełne menu <ArrowRight size={18}/></a></div><div className="mx-auto w-full max-w-sm"><div className="relative aspect-[4/5] overflow-hidden rounded-[2.25rem] bg-sky-300 shadow-2xl ring-1 ring-white/30">{menuSlides.map((slide, index) => <img key={slide.image} src={slide.image} alt={index === menuSlide ? slide.alt : ''} aria-hidden={index !== menuSlide} loading="lazy" className={`absolute inset-0 h-full w-full object-cover transition duration-700 ${index === menuSlide ? 'scale-100 opacity-100' : 'scale-105 opacity-0'}`}/>) }<div className="absolute inset-x-4 bottom-4 flex items-center justify-between gap-3 rounded-2xl bg-slate-950/75 p-3 backdrop-blur-md"><button type="button" onClick={() => setMenuSlide((slide) => (slide - 1 + menuSlides.length) % menuSlides.length)} aria-label="Poprzednie zdjęcie" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 transition hover:bg-white/25"><ChevronLeft size={18}/></button><p className="text-center text-sm font-extrabold">{menuSlides[menuSlide].label}</p><button type="button" onClick={() => setMenuSlide((slide) => (slide + 1) % menuSlides.length)} aria-label="Następne zdjęcie" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 transition hover:bg-white/25"><ChevronRight size={18}/></button></div></div><div className="mt-4 flex justify-center gap-2">{menuSlides.map((slide, index) => <button key={slide.image} type="button" onClick={() => setMenuSlide(index)} aria-label={`Pokaż zdjęcie ${index + 1}: ${slide.label}`} aria-current={index === menuSlide} className={`h-2 rounded-full transition-all ${index === menuSlide ? 'w-7 bg-white' : 'w-2 bg-white/45 hover:bg-white/70'}`}/>)}</div></div></div></div></section>

      <section id="rules" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Koci savoir-vivre</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Kilka zasad.<br/>Dużo spokoju.</h2><p className="mt-5 max-w-md leading-relaxed text-slate-600">To dom naszych rezydentów. Proste reguły sprawiają, że wszystkim — na dwóch i czterech łapach — jest tu dobrze.</p><ul className="mt-8 space-y-3">{rules.map((rule) => <li key={rule} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-sky-100 text-sky-600"><Check size={14}/></span><span className="text-sm font-semibold leading-relaxed text-slate-700">{rule}</span></li>)}</ul></div><div><div className="mb-5 flex items-center justify-between"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">FAQ pierwszej wizyty</span><h3 className="mt-2 text-3xl font-black tracking-tight">Dobrze wiedzieć przed przyjściem.</h3></div><ShieldCheck className="hidden text-sky-500 sm:block" size={30}/></div><div className="space-y-3">{faqItems.map(({ question, answer }) => <details key={question} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-extrabold text-slate-800 marker:hidden"><span>{question}</span><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-sky-100 text-sky-600 text-xl leading-none transition group-open:rotate-45">+</span></summary><p className="pt-4 text-sm leading-relaxed text-slate-600">{answer}</p></details>)}</div></div></div></section>

      <section id="visit" className="mx-auto max-w-6xl px-5 pb-24 pt-10 sm:px-8"><div className="grid overflow-hidden rounded-[3rem] bg-white shadow-xl lg:grid-cols-[1fr_.9fr]"><div className="p-7 sm:p-12"><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">Zanim wpadniesz</span><h2 className="mt-3 text-4xl font-black tracking-tight">Zaplanuj miękkie lądowanie.</h2><div className="mt-9 space-y-5"><Info icon={Clock3} title="Wt–Pt 11:00–20:00 · Sob–Nd 10:00–20:00" text="W poniedziałki lokal jest zamknięty — to dzień ciszy dla kotów."/><Info icon={MapPin} title="ul. Krakowska 32, 45-075 Opole" text="5 minut spacerem od opolskiego Rynku · adres koncepcyjny."/><Info icon={CalendarDays} title="Stoliki na 90 minut" text="W weekend rezerwacja zalecana. Dzieci od 8 lat, zawsze pod opieką dorosłego."/></div><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => setBookingOpen(true)} className="flex items-center gap-2 rounded-full bg-sky-500 px-6 py-3.5 font-bold text-white transition hover:-translate-y-1 hover:bg-sky-600">Zarezerwuj stolik <CalendarDays size={18}/></button><button onClick={() => setChatOpen(true)} className="flex items-center gap-2 rounded-full border border-slate-300 px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">Zapytaj asystenta <MessageCircle size={18}/></button><a href="https://www.openstreetmap.org/search?query=Krakowska%2032%20Opole" target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-slate-300 px-6 py-3.5 font-bold hover:border-sky-400 hover:text-sky-600">Pokaż mapę <MapPin size={18}/></a></div></div><div className="relative min-h-[380px]"><img src="https://images.unsplash.com/photo-1511081692775-05d0f180a065?q=85&w=1200&auto=format&fit=crop" alt="Przytulne wnętrze kawiarni" loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/35 to-transparent"/></div></div></section>
      <section id="support" className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><span className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[.2em] text-sky-400"><HeartHandshake size={17}/> Dla naszych kotów</span><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight sm:text-5xl">Mały gest.<br/>Dużo spokoju.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-slate-300">Opieka weterynaryjna, karma i spokojne kryjówki są ważniejsze niż kolejna zabawka. Wybierz sposób, w jaki chcesz dołożyć swoją cegiełkę.</p><button type="button" onClick={() => setSupportOpen(true)} className="mt-8 inline-flex items-center gap-2 rounded-full bg-amber-300 px-6 py-3.5 font-extrabold text-amber-950 transition hover:-translate-y-1 hover:bg-amber-200">Wesprzyj koty <HeartHandshake size={18}/></button></div><div className="grid gap-3 sm:grid-cols-3">{[['Wirtualna kawa','15 zł','na codzienną opiekę'],['Miska na dziś','35 zł','na karmę i żwirek'],['Wsparcie leczenia','100 zł','na badania i wizyty']].map(([title, amount, text]) => <button key={title} type="button" onClick={() => setSupportOpen(true)} className="rounded-3xl border border-white/10 bg-white/10 p-5 text-left transition hover:-translate-y-1 hover:bg-white/15"><Coffee className="text-amber-300" size={20}/><p className="mt-6 text-sm font-bold text-slate-300">{title}</p><p className="mt-1 text-3xl font-black">{amount}</p><p className="mt-2 text-xs leading-relaxed text-slate-400">{text}</p></button>)}</div></div><div className="mt-12 grid gap-5 rounded-[2.5rem] bg-white p-7 text-slate-950 sm:p-9 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[.18em] text-sky-600"><ShoppingBasket size={17}/> Lista potrzeb</p><h3 className="mt-3 text-3xl font-black">Co przyda się najbardziej?</h3><p className="mt-3 leading-relaxed text-slate-600">Rzeczy można przynieść po wcześniejszym kontakcie z obsługą. Najpierw sprawdzimy, czego aktualnie potrzebują koty.</p></div><ul className="grid gap-2 sm:grid-cols-2">{['mokra karma dobrej jakości','żwirek bentonitowy bez zapachu','polarowe koce i ręczniki','transportery w dobrym stanie','preparaty na pchły i kleszcze','środki do bezpiecznego sprzątania'].map((item) => <li key={item} className="flex items-center gap-3 rounded-2xl bg-sky-50 px-4 py-3 text-sm font-bold text-slate-700"><Check size={16} className="shrink-0 text-emerald-500"/>{item}</li>)}</ul></div></div></section>
      <section id="events" className="bg-sky-50 py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-600">В календаре котокафе</span><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">События, ради которых хочется вернуться.</h2></div><p className="max-w-md text-slate-600">Маленькие встречи в спокойном ритме. Места на события ограничены, поэтому лучше зарегистрироваться заранее.</p></div><div className="grid gap-4 md:grid-cols-2">{events.map(({ icon: Icon, tag, title, text, meta }) => <article key={title} className="group rounded-[2rem] border border-sky-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg sm:p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-100 text-sky-600"><Icon size={22}/></span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-extrabold text-amber-800">{tag}</span></div><h3 className="mt-6 text-2xl font-black">{title}</h3><p className="mt-3 min-h-12 text-sm leading-relaxed text-slate-600">{text}</p><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="text-xs font-extrabold text-slate-500">{meta}</span><button type="button" onClick={() => setBookingOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white transition hover:bg-sky-600">Записаться <ArrowRight size={15}/></button></div></article>)}</div></div></section>

    </main>

    <footer className="border-t border-slate-200 bg-white py-10"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-5 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div className="flex items-center gap-2 font-extrabold"><Cat className="text-sky-500"/> Niebieski Kot.</div><div className="text-sm text-slate-500"><p>ul. Krakowska 32 · Opole · czesc@niebieskikot-opole.pl</p><p className="mt-1 text-xs">Projekt koncepcyjny — adres, kontakt i bohaterowie są demonstracyjne.</p></div><a href="https://www.instagram.com/niebieskikot.opole" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-bold hover:text-sky-600"><Instagram size={18}/> @niebieskikot.opole</a></div></footer>

    <div className="fixed bottom-5 right-5 z-50">{chatOpen && <div className="mb-3 flex h-[min(520px,calc(100vh-110px))] w-[calc(100vw-40px)] max-w-[370px] flex-col overflow-hidden rounded-[2rem] border border-sky-100 bg-white/95 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between bg-slate-950 px-5 py-4 text-white"><div><b className="block text-sm">Niebieski Asystent</b><span className="mt-0.5 flex items-center gap-1 text-[10px] text-slate-300"><ShieldCheck size={10}/> szybkie odpowiedzi</span></div><button onClick={() => setChatOpen(false)} aria-label="Zamknij czat" className="rounded-full p-2 hover:bg-white/10"><X size={18}/></button></div><div ref={scrollRef} className="flex-1 space-y-4 overflow-y-auto p-5">{messages.map((m,i) => <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : ''}`}><div className={`max-w-[86%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${m.role === 'user' ? 'rounded-br-sm bg-sky-500 text-white' : 'rounded-bl-sm bg-slate-100'}`}>{m.content}</div></div>)}{loading && <div className="w-fit rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-400">Piszę…</div>}</div><div className="flex gap-2 border-t p-3"><input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} maxLength={200} aria-label="Wiadomość do asystenta" placeholder="Napisz wiadomość…" className="min-w-0 flex-1 rounded-full bg-slate-100 px-4 text-sm outline-none focus:ring-2 focus:ring-sky-400"/><button onClick={send} disabled={loading || !input.trim()} aria-label="Wyślij wiadomość" className="grid h-11 w-11 place-items-center rounded-full bg-sky-500 text-white disabled:opacity-40"><Send size={17}/></button></div></div>}<button onClick={() => setChatOpen(!chatOpen)} aria-label={chatOpen ? 'Zamknij czat' : 'Otwórz czat'} className="ml-auto grid h-14 w-14 place-items-center rounded-full bg-sky-500 text-white shadow-xl shadow-sky-500/30 transition hover:scale-105">{chatOpen ? <X/> : <MessageCircle/>}</button></div>
    <BookingModal open={bookingOpen} onClose={closeBooking}/><SupportModal open={supportOpen} onClose={closeSupport}/>
  </div>;
}

function Info({ icon: Icon, title, text }) { return <div className="flex gap-4"><Icon className="mt-1 shrink-0 text-sky-500"/><div><p className="font-extrabold">{title}</p><p className="text-sm text-slate-500">{text}</p></div></div>; }
