import React from 'react';
import { ArrowLeft, CalendarDays, Cat, Check, Clock3, Heart, Home, ShieldCheck, Sparkles, Stethoscope } from 'lucide-react';

const facts = [
  { icon: CalendarDays, label: 'Wiek', value: '2 lata', note: 'urodzony około 18 maja 2024' },
  { icon: Home, label: 'Z nami od', value: '3 lutego 2026', note: 'przyjechał z domu tymczasowego' },
  { icon: Stethoscope, label: 'Zdrowie', value: 'Gotowy do adopcji', note: 'regularnie kontrolowany' },
  { icon: Heart, label: 'Status', value: 'Szuka domu', note: 'po okresie zapoznawczym' },
];

const health = ['szczepienia podstawowe aktualne', 'odrobaczony i zabezpieczony przeciw pasożytom', 'wykastrowany', 'zaczipowany', 'testy FIV/FeLV ujemne'];
const likes = ['wędki z piórkami', 'papierowe kulki', 'kartonowe pudełka', 'obserwowanie ulicy z parapetu', 'krótkie drzemki pod stolikiem', 'smaczki z kurczakiem'];
const boundaries = ['nie lubi gwałtownego podnoszenia', 'potrzebuje chwili przy nowych osobach', 'głośne zabawki szybko go męczą', 'miska powinna stać z dala od kuwety'];

export default function CatProfilePage() {
  return <div className="min-h-screen bg-[#f7f8f4] text-slate-950 selection:bg-sky-200">
    <nav className="sticky top-0 z-40 border-b border-white/60 bg-[#f7f8f4]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-8"><a href="/" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-sky-500 text-white"><Cat size={19}/></span><span className="text-lg font-extrabold tracking-tight">Niebieski Kot<span className="text-sky-500">.</span></span></a><a href="/#cats" className="flex items-center gap-2 rounded-full border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold transition hover:border-sky-400 hover:text-sky-600"><ArrowLeft size={16}/> Wszystkie koty</a></div></nav>

    <main>
      <header className="mx-auto grid max-w-6xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-20">
        <div className="relative"><div className="aspect-[4/5] overflow-hidden rounded-[3rem] bg-sky-100 shadow-2xl"><img src="https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=88&w=1200&auto=format&fit=crop" alt="Pixel — młody kot szukający domu" className="h-full w-full object-cover"/></div><span className="absolute bottom-5 left-5 flex items-center gap-2 rounded-full bg-amber-300 px-4 py-2.5 text-sm font-black text-amber-950 shadow-lg"><Heart size={16} fill="currentColor"/> Szuka domu</span></div>
        <div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-sky-600">Poznaj naszego rezydenta</p><h1 className="mt-4 text-7xl font-black tracking-[-.05em] sm:text-8xl">Pixel<span className="text-sky-500">.</span></h1><p className="mt-5 text-xl font-bold text-slate-700">Ciekawski łowca wędek i zawodowy inspektor kartonów.</p><p className="mt-5 max-w-xl leading-relaxed text-slate-600">Pixel jest energiczny, kontaktowy i bardzo czytelnie pokazuje swoje granice. Najpierw obserwuje człowieka, a kiedy poczuje się bezpiecznie — przynosi zabawkę i zaprasza do wspólnej zabawy.</p><div className="mt-8 rounded-3xl border border-sky-200 bg-sky-50 p-5"><p className="flex items-center gap-2 font-extrabold text-sky-800"><Sparkles size={18}/> Najkrócej o Pixelu</p><p className="mt-2 text-sm leading-relaxed text-sky-950/70">Towarzyski, ale nienachalny. Aktywny rano i późnym popołudniem. Najlepiej odnajdzie się w spokojnym domu, który da mu czas na aklimatyzację.</p></div></div>
      </header>

      <section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{facts.map(({icon:Icon,label,value,note}) => <article key={label} className="rounded-3xl border border-slate-200 bg-white p-6"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-100 text-sky-600"><Icon size={20}/></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.16em] text-slate-400">{label}</p><h2 className="mt-1 text-xl font-black">{value}</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">{note}</p></article>)}</div></section>

      <section className="bg-slate-950 py-20 text-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-sky-400">Jego historia</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Od nieśmiałego gościa do duszy kawiarni.</h2></div><div className="space-y-5 text-lg leading-relaxed text-slate-300"><p>Pixel nie urodził się w kawiarni. Został znaleziony jako młody kot na opolskich ogródkach działkowych, a następnie trafił pod opiekę lokalnego domu tymczasowego.</p><p>Do Niebieskiego Kota przyjechał 3 lutego 2026 roku. Pierwsze dwa dni spędził w spokojnym pokoju adaptacyjnym. Trzeciego dnia sam wyszedł zwiedzić salę, a tydzień później odkrył swoją ulubioną kryjówkę pod stolikiem przy oknie.</p><p>Jego data urodzenia jest orientacyjna — lekarz weterynarii oszacował ją na maj 2024 roku na podstawie uzębienia i ogólnego rozwoju.</p></div></div></section>

      <section className="mx-auto grid max-w-6xl gap-5 px-5 py-20 sm:px-8 lg:grid-cols-2"><article className="rounded-[2.5rem] bg-white p-7 sm:p-9"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-emerald-600">Zdrowie</p><h2 className="mt-3 text-3xl font-black">Karta weterynaryjna</h2><p className="mt-4 leading-relaxed text-slate-600">Pixel jest pod regularną kontrolą lekarza i nie wymaga obecnie stałego leczenia ani specjalistycznej diety.</p><ul className="mt-7 space-y-3">{health.map((item) => <li key={item} className="flex gap-3 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-950"><Check size={18} className="shrink-0 text-emerald-600"/>{item}</li>)}</ul></article>
        <article className="rounded-[2.5rem] bg-sky-500 p-7 text-white sm:p-9"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-sky-100">Charakter</p><h2 className="mt-3 text-3xl font-black">Jak się z nim zaprzyjaźnić?</h2><p className="mt-4 leading-relaxed text-sky-50">Usiądź bokiem, połóż zabawkę niedaleko siebie i pozwól mu wykonać pierwszy krok. Pixel szybko uczy się rytuałów i chętnie wraca do osób, które szanują jego sygnały.</p><div className="mt-7 grid grid-cols-3 gap-3 text-center"><Trait value="9/10" label="ciekawość"/><Trait value="8/10" label="zabawa"/><Trait value="6/10" label="przytulanie"/></div><p className="mt-7 rounded-2xl bg-white/15 p-4 text-sm leading-relaxed ring-1 ring-white/20"><strong>Sygnał „mam dość”:</strong> Pixel odwraca głowę i macha końcówką ogona. Wtedy najlepiej zrobić przerwę.</p></article></section>

      <section className="mx-auto grid max-w-6xl gap-5 px-5 pb-20 sm:px-8 lg:grid-cols-2"><ListCard title="Co kocha" intro="Te rzeczy prawie zawsze poprawiają mu humor." items={likes} tone="amber"/><ListCard title="Co warto uszanować" intro="Kilka prostych zasad pomaga mu czuć się bezpiecznie." items={boundaries} tone="slate"/></section>

      <section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8"><div className="grid gap-10 rounded-[3rem] border border-slate-200 bg-white p-7 sm:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-sky-600">Typowy dzień</p><h2 className="mt-3 text-4xl font-black tracking-tight">Rytm Pixela.</h2><p className="mt-4 leading-relaxed text-slate-600">Regularny plan pozwala mu odpocząć między spotkaniami z gośćmi.</p></div><div className="space-y-4"><Routine time="08:30" text="Śniadanie i krótka kontrola samopoczucia."/><Routine time="10:00" text="Najbardziej energiczna zabawa z opiekunem."/><Routine time="12:00–15:00" text="Drzemka w cichym miejscu poza salą."/><Routine time="16:00" text="Obserwowanie gości i polowanie na wędkę."/><Routine time="19:30" text="Kolacja, wyciszenie i nocny obchód kartonów."/></div></div></section>

      <section className="mx-auto max-w-6xl px-5 pb-24 sm:px-8"><div className="overflow-hidden rounded-[3rem] bg-amber-300 p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-amber-900">Idealny dom</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Spokojny, uważny i gotowy na zabawę.</h2><p className="mt-5 max-w-2xl leading-relaxed text-amber-950/75">Pixel może zamieszkać ze spokojnym dorosłym kotem po prawidłowym zapoznaniu. Preferujemy dom bez bardzo małych dzieci, z zabezpieczonymi oknami i minimum dwiema krótkimi sesjami zabawy dziennie.</p></div><div className="rounded-3xl bg-white/65 p-5"><p className="flex items-center gap-2 font-black"><ShieldCheck size={19}/> Proces adopcji</p><p className="mt-2 text-sm leading-relaxed text-amber-950/70">Rozmowa, ankieta, spotkanie z Pixelem i wizyta przedadopcyjna. Umowa oraz kontakt po adopcji są częścią procesu.</p></div></div></div></section>

      <p className="mx-auto max-w-2xl px-5 pb-10 text-center text-xs leading-relaxed text-slate-500">Pixel, jego historia i dane zdrowotne są elementem projektu koncepcyjnego. Nie opisują prawdziwego zwierzęcia i nie stanowią rzeczywistego ogłoszenia adopcyjnego.</p>
    </main>
  </div>;
}

function Trait({ value, label }) { return <div className="rounded-2xl bg-white/15 p-3 ring-1 ring-white/20"><strong className="block text-xl">{value}</strong><span className="text-xs text-sky-100">{label}</span></div>; }
function ListCard({ title, intro, items, tone }) { const warm = tone === 'amber'; return <article className={`rounded-[2.5rem] p-7 sm:p-9 ${warm ? 'bg-amber-100' : 'bg-slate-200'}`}><h2 className="text-3xl font-black">{title}</h2><p className="mt-3 text-slate-600">{intro}</p><ul className="mt-6 flex flex-wrap gap-2">{items.map((item) => <li key={item} className={`rounded-full px-4 py-2 text-sm font-bold ${warm ? 'bg-white text-amber-950' : 'bg-white text-slate-800'}`}>{item}</li>)}</ul></article>; }
function Routine({ time, text }) { return <div className="flex gap-4 rounded-2xl bg-slate-50 p-4"><span className="flex shrink-0 items-center gap-2 font-black text-sky-600"><Clock3 size={17}/>{time}</span><p className="text-sm leading-relaxed text-slate-600">{text}</p></div>; }
